DBServer: dallocate.c File Reference
dallocate.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "parser.h"
#include "dallocate.h"
#include "global.h"
Functions
void free_cfgframe_object (struct cfg_frame *cfg)
void free_2darray_l (long int **array, int x)
void free_2darray (unsigned char **array, int x)
Function Documentation
void free_2darray (unsigned char ** array, int x)
Definition at line 109 of file dallocate.c.
Referenced by free_cfgframe_object().
{
int i;
 for(i=0; i<x; i++)
    free(array[i]);
 free(array);
}
void free_2darray_l (long int ** array, int x)
Definition at line 96 of file dallocate.c.
{
int i;
 for(i=0; i<x; i++)
    free(array[i]);
 free(array);
}
void free_cfgframe_object (struct cfg_frame * cfg)
Definition at line 52 of file dallocate.c.
References channel_names::angnames, for_each_pmu::annmr, for_each_pmu::cnext, dgnames::dg_next, dgnames::dgn, for_each_pmu::dgnmr, for_each_pmu::dgunit, channel_names::first, free_2darray(), channel_names::phnames, for_each_pmu::phnmr, and cfg_frame::pmu.
Referenced by cfgparser().
{
        int num_pmu,j = 0,i = 0;
        int phn,ann,dgn;
        struct dgnames *t_dgnames,*r_dgnames;
        printf("Inside free_cfgframe_object()\n");
        while(j<cfg->num_pmu) {
                if(cfg->pmu[j]->phnmr != 0)
                free_2darray(cfg->pmu[j]->cnext->phnames,cfg->pmu[j]->phnmr);
                if(cfg->pmu[j]->annmr != 0)
                free_2darray(cfg->pmu[j]->cnext->angnames,cfg->pmu[j]->annmr);
                if(cfg->pmu[j]->dgnmr != 0) {
                        t_dgnames = cfg->pmu[j]->cnext->first;
                        while(t_dgnames != NULL) {
                                r_dgnames = t_dgnames->dg_next;
                                free_2darray(t_dgnames->dgn,16);
                                t_dgnames = r_dgnames;
                        }
                }
//              free_2darray_l(cfg->pmu[j]->phunit,cfg->pmu[j]->phnmr);
//              free_2darray_l(cfg->pmu[j]->anunit,cfg->pmu[j]->annmr);
                if(cfg->pmu[j]->dgnmr != 0)
                        free_2darray(cfg->pmu[j]->dgunit,cfg->pmu[j]->dgnmr);
                j++;
        } // End of While
        free(cfg);
}