iPDC-(PhasorDataConcentrator): new_pmu_or_pdc.c File Reference
new_pmu_or_pdc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <signal.h>
#include <pthread.h>
#include <time.h>
#include <ctype.h>
#include <gtk/gtk.h>
#include "ipdcGui.h"
#include "connections.h"
#include "parser.h"
#include "global.h"
#include "new_pmu_or_pdc.h"
#include "dallocate.h"
Functions
int add_PMU (char pmuid[], char ip[], char port[], char protocol[])
void * connect_pmu_tcp (void *temp)
void * connect_pmu_udp (void *temp)
void add_PMU_Node (struct Lower_Layer_Details *temp_pmu)
int remove_Lower_Node (char pmuid[], char protocol[])
void * remove_llnode (void *temp)
void remove_cfg_from_file (unsigned char idcode[])
int put_data_transmission_off (char pmuid[], char protocol[])
void * data_off_llnode (void *temp)
int put_data_transmission_on (char pmuid[], char protocol[])
void * data_on_llnode (void *temp)
int configuration_request (char pmuid[], char protocol[])
void * config_request (void *temp)
int add_PDC (char ip[], char protocol[])
int remove_PDC (char ip[], char port_num[], char protocol[])
void display_CT ()
void create_command_frame (int type, int pmu_id, char cmdframe[])
int checkip (char ip[])
Function Documentation
int add_PDC (char ip[], char protocol[])
Definition at line 1316 of file new_pmu_or_pdc.c.
References Upper_Layer_Details::address_set, Upper_Layer_Details::config_change, i, Upper_Layer_Details::ip, mutex_Upper_Layer_Details, Upper_Layer_Details::next, Upper_Layer_Details::pdc_addr, Upper_Layer_Details::port, Upper_Layer_Details::prev, Upper_Layer_Details::protocol, TCPPORT, UDPPORT, Upper_Layer_Details::UL_data_transmission_off, Upper_Layer_Details::UL_upper_pdc_cfgsent, ULfirst, and ULlast.
Referenced by new_pdc_validation().
{
        FILE *f_ip;
        int flag = 0;
        char port_num[6], line [30]; /* or other suitable maximum line size */
        char *p,*i,*port;
        f_ip = fopen("upperpdc_ip.txt","r");
        memset(line,'\0',30);
        if(f_ip != NULL) { //1 if
                 while (fgets (line, 30,f_ip) != NULL) /* read a line */{ //2 if
                        i = strtok (line," ");
                        port = strtok (NULL," ");
                        p = strtok (NULL," ");
                        if(!strcmp(i,ip) && (!strncasecmp(p,protocol,3))){
                                flag = 1;
                                printf("MATCH\n");
                                return 1;
                        }
                }// 2. if
                fclose (f_ip);
        } else {
                printf("file upperpdc_ip.txt not present\n Created upperpdc_ip.txt\n");
                f_ip = fopen("upperpdc_ip.txt","w"); // File is not present so create it
                fclose(f_ip);
        }
        printf("flag = %d\n",flag);
        f_ip = fopen("upperpdc_ip.txt","a");
        fprintf(f_ip,"%s",ip);
        fputc(' ',f_ip);
        if(!strncasecmp(protocol,"TCP",3)) {
                sprintf(port_num,"%d",TCPPORT);
                fprintf(f_ip,"%s",port_num);
                fputc(' ',f_ip);
        } else {
                sprintf(port_num,"%d",UDPPORT);
                fprintf(f_ip,"%s",port_num);
                fputc(' ',f_ip);
        }
        fprintf(f_ip,"%s",protocol);
        fputc('\n',f_ip);
        fclose(f_ip);
        /* Make a node that contains PDC IP,Port and Protocol */
        struct Upper_Layer_Details *temp_pdc;
        temp_pdc = malloc(sizeof(struct Upper_Layer_Details));
        if(!temp_pdc) {
                printf("Not enough memory temp_pdc\n");
                exit(1);
        }
        strcpy(temp_pdc->ip,ip);     // ip
        if(!strncasecmp(protocol,"UDP",3)) {
                temp_pdc->port = UDPPORT;   // port
        } else {
                temp_pdc->port = TCPPORT;   // port
        }
        strncpy(temp_pdc->protocol,protocol,3); // protocol
        temp_pdc->protocol[3] = '\0';
        bzero(&temp_pdc->pdc_addr,sizeof(temp_pdc->pdc_addr));
        temp_pdc->pdc_addr.sin_family = AF_INET;
        temp_pdc->pdc_addr.sin_addr.s_addr =  inet_addr(temp_pdc->ip);
        temp_pdc->pdc_addr.sin_port = htons(temp_pdc->port);
        memset(&(temp_pdc->pdc_addr.sin_zero), '\0', 8);   // zero the rest of the struct
        temp_pdc->config_change = 0;
        temp_pdc->UL_upper_pdc_cfgsent = 0;
        temp_pdc->UL_data_transmission_off = 1;
        temp_pdc->address_set = 0;
        printf("PDC IP ADRESS = %s\n",inet_ntoa(temp_pdc->pdc_addr.sin_addr));
        pthread_mutex_lock(&mutex_Upper_Layer_Details);
        if(ULfirst == NULL) {
                ULfirst = temp_pdc;
                temp_pdc->prev = NULL;
        } else {
                ULlast->next = temp_pdc;
                temp_pdc->prev = ULlast;
        }
        ULlast = temp_pdc;
        temp_pdc->next = NULL;
        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
        return 0;
//   }//not matched-else
}
int add_PMU (char pmuid[], char ip[], char port[], char protocol[])
Definition at line 86 of file new_pmu_or_pdc.c.
References Upper_Layer_Details::config_change, connect_pmu_tcp(), connect_pmu_udp(), Lower_Layer_Details::data_transmission_off, i, Lower_Layer_Details::ip, mutex_Upper_Layer_Details, Upper_Layer_Details::next, Lower_Layer_Details::next, Lower_Layer_Details::pmu_remove, Lower_Layer_Details::pmuid, Lower_Layer_Details::port, Lower_Layer_Details::prev, Lower_Layer_Details::protocol, Lower_Layer_Details::request_cfg_frame, ULfirst, and Lower_Layer_Details::up.
Referenced by add_pmu_validation().
{
        FILE *f_ip;
        int flag = 0;
        char *i,*p,*port_num,*id;
        int err;
        // A new thread is created for each TCP connection in 'detached' mode. Thus allowing any number of threads to be created.
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        f_ip = fopen("ipaddress.txt","r");
        char line [40]; /* or other suitable maximum line size */
        memset(line,'\0',40);
        if(f_ip != NULL) { //1 if
                 while (fgets (line, 40,f_ip) != NULL) /* read a line */{ //2 while
                        id = strtok (line," ");
                        i = strtok (NULL," ");
                        port_num = strtok (NULL," ");
                        p = strtok (NULL," ");
                        if(!strcmp(id,pmuid)) {
                                flag = 1;
                                break;
                        } else {
                                memset(line,'\0',30);
                                continue;
                        }
                }// 2. while ends
                        fclose (f_ip);
        } else {
                        printf("File ipaddress.txt not present so we create it\n");
                        f_ip = fopen("ipaddress.txt","w"); // File is not present so create it
                        fclose(f_ip);
        }
        printf("flag = %d\n",flag);
        if(flag)  { /* 2 if there is a match */
                printf("%s %s is already in the ipaddress list Enter another PMU\n",pmuid,protocol);
                return 1;
        } else if(!flag) {
                f_ip = fopen("ipaddress.txt","a");
                fprintf(f_ip,"%s",pmuid);
                fputc(' ',f_ip);
                fprintf(f_ip,"%s",ip);
                fputc(' ',f_ip);
                fprintf(f_ip,"%s",port);
                fputc(' ',f_ip);
                fprintf(f_ip,"%s",protocol);
                fputc('\n',f_ip);
                fclose(f_ip);
                /* Make a node that contains PMU IP, Port and  Protocol details */
                struct Lower_Layer_Details *temp_pmu;
                temp_pmu = malloc(sizeof(struct Lower_Layer_Details));
                if(!temp_pmu) {
                        printf("Not enough memory temp_pmu\n");
                        exit(1);
                }
                temp_pmu->pmuid = atoi(pmuid); // PMUID
                strcpy(temp_pmu->ip,ip); // ip
                temp_pmu->port = atoi(port); // port
                strcpy(temp_pmu->protocol,protocol); // protocol
                temp_pmu->protocol[3] = '\0';
                temp_pmu->up = 1;
                temp_pmu->data_transmission_off = 0;
                temp_pmu->pmu_remove = 0;
                temp_pmu->request_cfg_frame = 0;
                temp_pmu->next = NULL;
                temp_pmu->prev = NULL;
                pthread_t t;
                if(!strncasecmp(protocol,"UDP",3)) {
                        if((err = pthread_create(&t,&attr,connect_pmu_udp,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                } else if(!strncasecmp(protocol,"TCP",3)) {
                        if((err = pthread_create(&t,&attr,connect_pmu_tcp,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                }
                struct Upper_Layer_Details *temp_pdc = ULfirst;
                pthread_mutex_lock(&mutex_Upper_Layer_Details);
                while(temp_pdc != NULL ) {
                        temp_pdc->config_change = 1;
                        temp_pdc = temp_pdc->next;
                }
                pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                return 0;
        } // If no match
        return 1;
}
void add_PMU_Node (struct Lower_Layer_Details * temp_pmu)
Definition at line 512 of file new_pmu_or_pdc.c.
References LLfirst, LLlast, mutex_Lower_Layer_Details, Lower_Layer_Details::next, and Lower_Layer_Details::prev.
Referenced by connect_pmu_tcp(), and connect_pmu_udp().
{
        pthread_mutex_lock(&mutex_Lower_Layer_Details);
        if(LLfirst == NULL) {
                temp_pmu->prev = NULL;
                LLfirst = temp_pmu;
        } else {
                LLlast->next = temp_pmu;
                temp_pmu->prev = LLlast;
        }
        temp_pmu->next = NULL;
        LLlast = temp_pmu;
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
}
int checkip (char ip[])
Definition at line 1694 of file new_pmu_or_pdc.c.
Referenced by add_pmu_validation(), new_pdc_validation(), remove_pdc_validation(), and validation_pdc_detail().
                       {
        struct sockaddr_in sa;
        int result = inet_pton(AF_INET, ip, &(sa.sin_addr));
        return result;
}
void* config_request (void * temp)
Definition at line 1230 of file new_pmu_or_pdc.c.
References Upper_Layer_Details::config_change, connect_pmu_tcp(), create_command_frame(), Lower_Layer_Details::data_transmission_off, Lower_Layer_Details::llpmu_addr, mutex_Upper_Layer_Details, Upper_Layer_Details::next, Lower_Layer_Details::pmuid, Lower_Layer_Details::protocol, Lower_Layer_Details::sockfd, ULfirst, and Lower_Layer_Details::up.
Referenced by configuration_request().
{
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        char *cmdframe = malloc(19);
        int err;
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        if(!strncasecmp(temp_pmu->protocol,"UDP",3)) { /* If Peer is UDP */
                cmdframe[18] = '\0';
                create_command_frame(1,temp_pmu->pmuid,cmdframe);
                int n;
                if ((n = sendto(temp_pmu->sockfd,cmdframe, 18,
                                         0,(struct sockaddr *)&temp_pmu->llpmu_addr,sizeof(temp_pmu->llpmu_addr)) == -1)) {
                              perror("sendto");
                } else {
                        printf("CmD to send CFG = %x\t%x\n", cmdframe[0], cmdframe[1]);
                        free(cmdframe);
                        temp_pmu->data_transmission_off = 0;
                }
        } else if(!strncasecmp(temp_pmu->protocol,"TCP",3)){ /* If Peer is TCP */
                int n;
                if(temp_pmu->up == 0) { /* If TCP Peer is DOWN */
                        pthread_t t;
                        if((err = pthread_create(&t,&attr,connect_pmu_tcp,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                        struct Upper_Layer_Details *temp_pdc = ULfirst;
                        pthread_mutex_lock(&mutex_Upper_Layer_Details);
                        while(temp_pdc != NULL ) {
                                temp_pdc->config_change = 1;
                                temp_pdc = temp_pdc->next;
                        }
                        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                } else { /* If TCP Peer is UP */
                        cmdframe[18] = '\0';
                        create_command_frame(1,temp_pmu->pmuid,cmdframe);
                        if ((n = send(temp_pmu->sockfd,cmdframe, 18,0) == -1)) {
                              printf("temp_pmu->sockfd %d \n",temp_pmu->sockfd);
                              perror("send");
                        } else {
                                printf("CmD to send CFG \n");
                                free(cmdframe);
                                temp_pmu->data_transmission_off = 0;
                        }
                }
        }
        pthread_exit(NULL);
}
int configuration_request (char pmuid[], char protocol[])
Definition at line 1157 of file new_pmu_or_pdc.c.
References config_request(), LLfirst, mutex_Lower_Layer_Details, Lower_Layer_Details::next, Lower_Layer_Details::pmuid, and Lower_Layer_Details::protocol.
Referenced by cmd_or_remove_pmu_validation().
{
        int flag = 0,err;
        // A new thread is created for each TCP connection in 'detached' mode. Thus allowing any number of threads to be created.
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        pthread_mutex_lock(&mutex_Lower_Layer_Details);
        if(LLfirst == NULL) {
                printf("No PMU Added\n");
                return 1;
        } else {
                flag = 1;
        }
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
        if(flag) {
                int match = 0;
                struct Lower_Layer_Details *temp_pmu = LLfirst;
                while(temp_pmu != NULL) {
                        if((temp_pmu->pmuid == atoi(pmuid)) && (!strncasecmp(temp_pmu->protocol,protocol,3))) {
                                match = 1;
                                break;
                        } else {
                                temp_pmu = temp_pmu->next;
                        }
                }
                if(match) {
//                      temp_pmu->request_cfg_frame = 1;
                        pthread_t t;
                        if((err = pthread_create(&t,&attr,config_request,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                        return 0;
                } else {
                        printf("No Match\n");
                        return 1;
                }
        }
        return 1;
}
void* connect_pmu_tcp (void * temp)
Definition at line 220 of file new_pmu_or_pdc.c.
References add_PMU_Node(), compute_CRC(), Upper_Layer_Details::config_change, copy_cbyc(), create_command_frame(), DB_Server_addr, DB_sockfd, fp_log, Lower_Layer_Details::ip, Lower_Layer_Details::llpmu_addr, MAXBUFLEN, mutex_Upper_Layer_Details, Upper_Layer_Details::next, PMU_process_TCP(), Lower_Layer_Details::pmuid, Lower_Layer_Details::port, Lower_Layer_Details::sockfd, Lower_Layer_Details::thread_id, to_intconvertor(), ULfirst, Lower_Layer_Details::up, and yes.
Referenced by add_PMU(), config_request(), and recreate_tcp_connections().
{
        int tcp_sockfd,port_num,yes = 1;
        struct sockaddr_in PMU_addr;
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        unsigned char *tcp_BUF,*ptr,length[2];
        unsigned int flen;
        uint16_t cal_crc,frame_crc;
        port_num = temp_pmu->port;
        if ((tcp_sockfd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
                perror("socket");
                exit(1);
        }
        if (setsockopt(tcp_sockfd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(int)) == -1) {
                perror("setsockopt");
                exit(1);
        }
        bzero(&PMU_addr,sizeof(PMU_addr));
        PMU_addr.sin_family = AF_INET;
        PMU_addr.sin_addr.s_addr =  inet_addr(temp_pmu->ip);
        PMU_addr.sin_port = htons(port_num);
        memset(&(PMU_addr.sin_zero), '\0', 8);   // zero the rest of the struct
        /* Copy the information of Lower Layer PMU/PDC to the node */
        temp_pmu->thread_id = pthread_self();
        bzero(&temp_pmu->llpmu_addr,sizeof(PMU_addr));
        temp_pmu->llpmu_addr.sin_family = AF_INET;
        temp_pmu->llpmu_addr.sin_addr.s_addr =  inet_addr(temp_pmu->ip);
        temp_pmu->llpmu_addr.sin_port = htons(port_num);
        memset(&(temp_pmu->llpmu_addr.sin_zero), '\0', 8);   // zero the rest of the struct
        temp_pmu->sockfd = tcp_sockfd;
        temp_pmu->up = 1;
        if (connect(tcp_sockfd, (struct sockaddr *)&PMU_addr,
                                        sizeof(PMU_addr)) == -1) { // Main if
                perror("connect");
                temp_pmu->up = 0;
                add_PMU_Node(temp_pmu);
                pthread_exit(NULL);
        } else {
                /* Add PMU*/
                add_PMU_Node(temp_pmu);
                tcp_BUF = malloc(MAXBUFLEN* sizeof(unsigned char));
                /* Sending Command fro obtaining CFG */
                int n,bytes_read;
                char *cmdframe = malloc(19);
                cmdframe[18] = '\0';
                create_command_frame(1,temp_pmu->pmuid,cmdframe);
                if ((n = send (tcp_sockfd,cmdframe,18,0) == -1)) {
                        perror("send");
                } else {
                        free(cmdframe);
                        while(1) {
                                memset(tcp_BUF, '\0', MAXBUFLEN * sizeof(unsigned char));
                                bytes_read = recv (tcp_sockfd, tcp_BUF,MAXBUFLEN-1,0);
                                if(bytes_read == 0) {  /* When  TCP Peer Terminates */
                                        printf("No data received Closing tcp socket %d\n",tcp_sockfd);
                                        temp_pmu->up = 0;
                                        struct Upper_Layer_Details *temp_pdc = ULfirst;
                                        pthread_mutex_lock(&mutex_Upper_Layer_Details);
                                        while(temp_pdc != NULL ) {
                                                temp_pdc->config_change = 1;
                                                temp_pdc = temp_pdc->next;
                                        }
                                        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                                        pthread_exit(NULL);
                                } else if(bytes_read == -1) {/* When  TCP Peer Terminates */
                                        perror("recv");
                                        temp_pmu->up = 0;
                                        struct Upper_Layer_Details *temp_pdc = ULfirst;
                                        pthread_mutex_lock(&mutex_Upper_Layer_Details);
                                        while(temp_pdc != NULL ) {
                                                temp_pdc->config_change = 1;
                                                temp_pdc = temp_pdc->next;
                                        }
                                        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                                 } else {
                                        ptr = tcp_BUF;
                                        ptr += 2;
                                        copy_cbyc(length,ptr,2);
                                        flen = to_intconvertor(length);
                                        cal_crc = compute_CRC(tcp_BUF,flen-2);
                                        ptr += flen -4;
                                        frame_crc = *ptr;
                                        frame_crc <<= 8;
                                        frame_crc |= *(ptr + 1);
                                        if(frame_crc != cal_crc) {
                                                fprintf(fp_log,"CRC NOT MATCH\n");
                                                continue;
                                        }
                                        if (sendto(DB_sockfd,tcp_BUF, MAXBUFLEN-1, 0,
                                                        (struct sockaddr *)&DB_Server_addr,sizeof(DB_Server_addr)) == -1) {
                                                perror("sendto");
                                        }
                                        tcp_BUF[bytes_read] = '\0';
                                        PMU_process_TCP(tcp_BUF,tcp_sockfd);
                                }
                        } // while ends
                }
        }// Main if
        close(tcp_sockfd);
        pthread_exit(NULL);
}
void* connect_pmu_udp (void * temp)
Definition at line 358 of file new_pmu_or_pdc.c.
References add_PMU_Node(), compute_CRC(), copy_cbyc(), create_command_frame(), DB_Server_addr, DB_sockfd, fp_log, Lower_Layer_Details::ip, LLfirst, Lower_Layer_Details::llpmu_addr, MAXBUFLEN, mutex_Lower_Layer_Details, Lower_Layer_Details::next, PMU_process_UDP(), Lower_Layer_Details::pmuid, Lower_Layer_Details::port, Lower_Layer_Details::protocol, Lower_Layer_Details::sockfd, Lower_Layer_Details::thread_id, to_intconvertor(), Lower_Layer_Details::up, and yes.
Referenced by add_PMU(), and recreate_udp_connections().
{
        int udp_sockfd,port_num,addr_len,yes = 1;
        struct sockaddr_in PMU_addr,their_addr;
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        struct Lower_Layer_Details *t ;
        unsigned char *udp_BUF,*ptr,length[2];
        unsigned int flen;
        uint16_t cal_crc,frame_crc;
        port_num = temp_pmu->port;
        if ((udp_sockfd = socket(AF_INET, SOCK_DGRAM, 0)) == -1) {
                perror("socket");
                exit(1);
        }
        if (setsockopt(udp_sockfd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(int)) == -1) {
                perror("setsockopt");
                exit(1);
        }
        bzero(&PMU_addr,sizeof(PMU_addr));
        PMU_addr.sin_family = AF_INET;
        PMU_addr.sin_addr.s_addr =  inet_addr(temp_pmu->ip);
        PMU_addr.sin_port = htons(port_num);
        memset(&(PMU_addr.sin_zero), '\0', 8);   // zero the rest of the struct
        /* Copy the information of Lower Layer PMU/PDC to the node */
        temp_pmu->thread_id = pthread_self();
        bzero(&temp_pmu->llpmu_addr,sizeof(PMU_addr));
        temp_pmu->llpmu_addr.sin_family = AF_INET;
        temp_pmu->llpmu_addr.sin_addr.s_addr =  inet_addr(temp_pmu->ip);
        temp_pmu->llpmu_addr.sin_port = htons(port_num);
        memset(&(temp_pmu->llpmu_addr.sin_zero), '\0', 8);   // zero the rest of the struct
        temp_pmu->sockfd = udp_sockfd;
        temp_pmu->up = 1;
        /* Add PMU*/
        add_PMU_Node(temp_pmu);
        udp_BUF = malloc(MAXBUFLEN* sizeof(unsigned char));
        /* Sending Command fro obtaining CFG */
        addr_len = sizeof(struct sockaddr);
        int n,bytes_read;
        unsigned char *cmdframe = malloc(19);
        cmdframe[18] = '\0';
        create_command_frame(1,temp_pmu->pmuid,(char *)cmdframe);
        if ((n = sendto(udp_sockfd,cmdframe, 18, 0,
                                (struct sockaddr *)&PMU_addr,sizeof(PMU_addr)) == -1)) {
                      perror("sendto");
        } else {
                free(cmdframe);
                fprintf(fp_log,"sent CMD for CFG\n");
                /* UDP data Received */
                while(1) {
                         memset(udp_BUF,'\0',MAXBUFLEN * sizeof(unsigned char));
                         bytes_read = recvfrom (udp_sockfd, udp_BUF,MAXBUFLEN-1,0,(struct sockaddr *)&their_addr,(socklen_t *)&addr_len);
                         if(bytes_read == -1) {
                                perror("recvfrom");
                                exit(1);
                         } else { // New Datagram received
                                pthread_mutex_lock(&mutex_Lower_Layer_Details);
                                int flag = 0;
                                if(LLfirst == NULL) {
                                        flag = 0;
                                } else {
                                        t = LLfirst;
                                        while(t != NULL) {
                                                if((!strcmp(t->ip,inet_ntoa(their_addr.sin_addr)))
                                                                && (!strncasecmp(t->protocol,"UDP",3))) {
                                                        flag = 1;
                                                        break;
                                                } else {
                                                        t = t->next;
                                                }
                                        }
                                }
                                pthread_mutex_unlock(&mutex_Lower_Layer_Details);
                                if(flag) {
                                        ptr = udp_BUF;
                                        ptr += 2;
                                        copy_cbyc(length,ptr,2);
                                        flen = to_intconvertor(length);
                                        cal_crc = compute_CRC(udp_BUF,flen-2);
                                        ptr += flen -4;
                                        frame_crc = *ptr;
                                        frame_crc <<= 8;
                                        frame_crc |= *(ptr + 1);
                                        if(frame_crc != cal_crc) {
                                                fprintf(fp_log,"CRC NOT MATCH\n");
                                                continue;
                                        }
                                        //process the frame
                                        int n;
                                        if ((n = sendto(DB_sockfd,udp_BUF, MAXBUFLEN-1, 0,
                                                        (struct sockaddr *)&DB_Server_addr,sizeof(DB_Server_addr)) == -1)) {
                                                perror("sendto");
                                        } else {
                                                fprintf(fp_log,"DB socket %d \n",DB_sockfd);
                                                fprintf(fp_log,"DB Server %s \n",inet_ntoa(DB_Server_addr.sin_addr));
                                                fprintf(fp_log,"UDP_BUF len %d Sent FRAME %d bytes\n",strlen((const char *)udp_BUF),n);
                                        }
                                        fprintf(fp_log,"\nUDP Server got packet from %s\n",inet_ntoa(their_addr.sin_addr));
                                        fprintf(fp_log,"packet is %d bytes long\n",bytes_read);
                                        udp_BUF[bytes_read] = '\0';
                                        //Call the udphandler
                                        PMU_process_UDP(udp_BUF,PMU_addr,udp_sockfd);
                                } else {
                                        printf("Datagram PMU not authentic. We donot pass the buffer for further processing %s\n",inet_ntoa(their_addr.sin_addr));
                                }
                        } // Main if ends
                } // while ends
        }
        close(udp_sockfd);
        pthread_exit(NULL);
}
void create_command_frame (int type, int pmu_id, char cmdframe[])
Definition at line 1611 of file new_pmu_or_pdc.c.
References byte_by_byte_copy(), CMDCFGSEND, CMDDATAOFF, CMDDATASEND, CMDSYNC, compute_CRC(), fp_log, int_to_ascii_convertor(), and long_int_to_ascii_convertor().
Referenced by config_request(), connect_pmu_tcp(), connect_pmu_udp(), data_off_llnode(), data_on_llnode(), PMU_process_TCP(), and PMU_process_UDP().
{
        fprintf(fp_log,"Inside create_command_frame()\n");
        memset(cmdframe,'\0',19);
        unsigned char fsize[2],pmuid[2],soc[4],fracsec[4];
        long int sec,frac = 0;
        int f = 18;
        uint16_t chk;
        memset(fsize,'\0',2);
        int_to_ascii_convertor(f,fsize);
        int_to_ascii_convertor(pmu_id,pmuid);
        fprintf(fp_log,"\nPMU ID = %d\n",pmu_id);
        sec = (long int)time (NULL);
        long_int_to_ascii_convertor(sec,soc);
        long_int_to_ascii_convertor(frac,fracsec);
        int index = 0;
                switch(type) {
                        case 1 : byte_by_byte_copy((unsigned char *)cmdframe,CMDSYNC,index,2); // SEND CFG
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fsize,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,pmuid,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,soc,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fracsec,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,CMDCFGSEND,index,2);
                                 index += 2;
                                 chk = compute_CRC((unsigned char *)cmdframe,index);
                                 cmdframe[index++] = (chk >> 8) & ~(~0<<8);     /* CHKSUM high byte; */
                                 cmdframe[index] = (chk ) & ~(~0<<8);           /* CHKSUM low byte;  */
                                 fprintf(fp_log,"Case 1\n");
                                 break;
                        case 2 : byte_by_byte_copy((unsigned char *)cmdframe,CMDSYNC,index,2);  // SEND DATA
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fsize,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,pmuid,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,soc,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fracsec,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,CMDDATASEND,index,2);
                                 index += 2;
                                 chk = compute_CRC((unsigned char *)cmdframe,index);
                                 cmdframe[index++] = (chk >> 8) & ~(~0<<8);     /* CHKSUM high byte; */
                                 cmdframe[index] = (chk ) & ~(~0<<8);           /* CHKSUM low byte;  */
                                 fprintf(fp_log,"Case 2\n");
                                 break;
                        case 3 : byte_by_byte_copy((unsigned char *)cmdframe,CMDSYNC,index,2);  // PUT OFF DATA TRANSMISSION
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fsize,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,pmuid,index,2);
                                 index += 2;
                                 byte_by_byte_copy((unsigned char *)cmdframe,soc,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,fracsec,index,4);
                                 index += 4;
                                 byte_by_byte_copy((unsigned char *)cmdframe,CMDDATAOFF,index,2);
                                 index += 2;
                                 chk = compute_CRC((unsigned char *)cmdframe,index);
                                 cmdframe[index++] = (chk >> 8) & ~(~0<<8);     /* CHKSUM high byte; */
                                 cmdframe[index] = (chk ) & ~(~0<<8);           /* CHKSUM low byte;  */
                                 fprintf(fp_log,"Case 3\n");
                                 break;
                        default: fprintf(fp_log,"Enter a Valid Request\n");
                                 break;
                }
}
void* data_off_llnode (void * temp)
Definition at line 972 of file new_pmu_or_pdc.c.
References create_command_frame(), Lower_Layer_Details::llpmu_addr, Lower_Layer_Details::pmuid, Lower_Layer_Details::protocol, Lower_Layer_Details::sockfd, and Lower_Layer_Details::up.
Referenced by put_data_transmission_off().
{
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        char *cmdframe = malloc(19);
        create_command_frame(3,temp_pmu->pmuid,cmdframe);
        cmdframe[18] = '\0';
        if(!strncasecmp(temp_pmu->protocol,"UDP",3)) {
                int n;
                if ((n = sendto(temp_pmu->sockfd,cmdframe, 18,
                                         0,(struct sockaddr *)&temp_pmu->llpmu_addr,sizeof(temp_pmu->llpmu_addr)) == -1)) {
                              perror("sendto");
                } else {
                        printf("Sent CmD to put off data transmission\n");
                }
        } else if(!strncasecmp(temp_pmu->protocol,"TCP",3)){
                int n;
                if(temp_pmu->up == 1) {
                        if ((n = send(temp_pmu->sockfd,cmdframe, 18,0) == -1)) {
                              perror("send");
                        } else {
                                printf("Sent CmD to put off data transmission\n");
                        }
                }
        }
        free(cmdframe);
        pthread_exit(NULL);
}
void* data_on_llnode (void * temp)
Definition at line 1114 of file new_pmu_or_pdc.c.
References create_command_frame(), Lower_Layer_Details::llpmu_addr, Lower_Layer_Details::pmuid, Lower_Layer_Details::protocol, Lower_Layer_Details::sockfd, and Lower_Layer_Details::up.
Referenced by put_data_transmission_on().
{
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        char *cmdframe = malloc(19);
        create_command_frame(2,temp_pmu->pmuid,cmdframe);
        cmdframe[18] = '\0';
        if(!strncasecmp(temp_pmu->protocol,"UDP",3)) {
                int n;
                if ((n = sendto(temp_pmu->sockfd,cmdframe, 18,
                                         0,(struct sockaddr *)&temp_pmu->llpmu_addr,sizeof(temp_pmu->llpmu_addr)) == -1)) {
                              perror("sendto");
                } else {
                        printf("Sent CmD to put on data transmission.\n");
                }
        } else if(!strncasecmp(temp_pmu->protocol,"TCP",3)){
                int n;
                if(temp_pmu->up == 1) {
                        if ((n = send(temp_pmu->sockfd,cmdframe, 18,0) == -1)) {
                              perror("send");
                        } else {
                                printf("Sent CmD to put on data transmission.\n");
                        }
                }
        }
        free(cmdframe);
        pthread_exit(NULL);
}
void display_CT ()
Definition at line 1552 of file new_pmu_or_pdc.c.
References Upper_Layer_Details::ip, Lower_Layer_Details::ip, LLfirst, mutex_Lower_Layer_Details, Upper_Layer_Details::next, Lower_Layer_Details::next, Lower_Layer_Details::pmuid, Upper_Layer_Details::port, Lower_Layer_Details::port, Upper_Layer_Details::protocol, Lower_Layer_Details::protocol, ULfirst, and Lower_Layer_Details::up.
                  {
        printf("####         CONNECTION TABLE OF SOURCE DEVICES        ####\n");
        printf("--------------------------------------------------------------------------------\n");
        printf("|   PMU ID      |       IP      |       Port    |     Protocol  |       Up      |\n");
        printf("--------------------------------------------------------------------------------\n");
        pthread_mutex_lock(&mutex_Lower_Layer_Details);
        if(LLfirst == NULL) {
                printf("No PMU Added\n");
        } else {
                struct Lower_Layer_Details *t = LLfirst;
                while(t != NULL) {
                        printf("|\t%d\t|%s\t|\t%d\t|\t%s\t|\t%d\t|\n",t->pmuid,t->ip,t->port,t->protocol,t->up);
                        t = t->next;
                }
                printf("--------------------------------------------------------------------------------\n");
        }
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
        printf("####  CONNECTION TABLE OF DESTINATION DEVICES  ####\n");
        printf("-------------------------------------------------\n");
        printf("|      IP       |       Port    |     Protocol  |\n");
        printf("-------------------------------------------------\n");
        if(ULfirst == NULL) {
                printf("No PDC Added\n");
        } else {
                struct Upper_Layer_Details *t = ULfirst;
                while(t != NULL) {
                        printf("|%s\t|\t%d\t|\t%s\t|\n",t->ip,t->port,t->protocol);
                        t = t->next;
                }
                printf("-------------------------------------------------\n");
        }
}
int put_data_transmission_off (char pmuid[], char protocol[])
Definition at line 877 of file new_pmu_or_pdc.c.
References data_off_llnode(), Lower_Layer_Details::data_transmission_off, fp_log, Lower_Layer_Details::ip, LLfirst, mutex_Lower_Layer_Details, Lower_Layer_Details::next, Lower_Layer_Details::pmuid, Lower_Layer_Details::port, and Lower_Layer_Details::protocol.
Referenced by cmd_or_remove_pmu_validation().
{
        int flag = 0,err;
        // A new thread is created for each TCP connection in 'detached' mode. Thus allowing any number of threads to be created.
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        printf("####   Connection TABLE   ####\n");
        printf("-----------------------------------------------------------------\n");
        printf("|   PMU ID      |        IP     |       Port    |     Protocol  |\n");
        printf("-----------------------------------------------------------------\n");
        pthread_mutex_lock(&mutex_Lower_Layer_Details);
        if(LLfirst == NULL) {
                printf("No PMU Added\n");
                return 1;
        } else {
                flag = 1;
                struct Lower_Layer_Details *t = LLfirst;
                while(t != NULL) {
                                printf("|\t%d\t|%s\t|\t%d\t|\t%s\t|\n",t->pmuid,t->ip,t->port,t->protocol);
                                t = t->next;
                }
                printf("-----------------------------------------------------------------\n");
        }
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
        if(flag) {
                int match = 0;
                struct Lower_Layer_Details *temp_pmu = LLfirst;
                while(temp_pmu != NULL) {
                        if((temp_pmu->pmuid == atoi(pmuid)) && (!strncasecmp(temp_pmu->protocol,protocol,3))) {
                                match = 1;
                                break;
                        } else {
                                temp_pmu = temp_pmu->next;
                        }
                }
                if(match) {
                        pthread_t t;
                        temp_pmu->data_transmission_off = 1;
                        if((err = pthread_create(&t,&attr,data_off_llnode,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                        return 0;
                } else {
                        fprintf(fp_log,"No Match\n");
                        return 1;
                }
        }
        return 1;
}
int put_data_transmission_on (char pmuid[], char protocol[])
Definition at line 1016 of file new_pmu_or_pdc.c.
References data_on_llnode(), Lower_Layer_Details::data_transmission_off, Lower_Layer_Details::ip, LLfirst, mutex_Lower_Layer_Details, Lower_Layer_Details::next, Lower_Layer_Details::pmuid, Lower_Layer_Details::port, and Lower_Layer_Details::protocol.
Referenced by cmd_or_remove_pmu_validation().
{
        int flag = 0,err;
        // A new thread is created for each TCP connection in 'detached' mode. Thus allowing any number of threads to be created.
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        printf("Lower Layer PMU/PDC whose data transmiision is off\n");
        printf("####   Connection TABLE   ####\n");
        printf("-----------------------------------------------------------------\n");
        printf("|   PMU ID      |       IP      |       Port    |     Protocol  |\n");
        printf("-----------------------------------------------------------------\n");
        pthread_mutex_lock(&mutex_Lower_Layer_Details);
        if(LLfirst == NULL) {
                printf("No PMU Added\n");
                return 1;
        } else {
                flag = 1;
                struct Lower_Layer_Details *t = LLfirst;
                while(t != NULL) {
                        if(t->data_transmission_off == 1) {
                                printf("|\t%d\t|%s\t|\t%d\t|\t%s\t|\n",t->pmuid,t->ip,t->port,t->protocol);
                        }
                        t = t->next;
                }
                printf("-----------------------------------------------------------------\n");
        }
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
        if(flag) {
                int match = 0;
                struct Lower_Layer_Details *temp_pmu = LLfirst;
                while(temp_pmu != NULL) {
                        if((temp_pmu->pmuid == atoi(pmuid)) && (!strncasecmp(temp_pmu->protocol,protocol,3))) {
                                match = 1;
                                break;
                        } else {
                                temp_pmu = temp_pmu->next;
                        }
                }
                if(match) {
                        temp_pmu->data_transmission_off = 0;
                        pthread_t t;
                        if((err = pthread_create(&t,&attr,data_on_llnode,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                        return 0;
                } else {
                        printf("No Match\n");
                        return 1;
                }
        }
        return 1;
}
void remove_cfg_from_file (unsigned char idcode[])
Definition at line 790 of file new_pmu_or_pdc.c.
References copy_cbyc(), fp_log, cfg_frame::framesize, ncmp_cbyc(), and to_intconvertor().
Referenced by remove_llnode().
{
        FILE *file,*newfile;
        int result;
        unsigned char id[3],*line,*s,frame_len[2];
        unsigned long fileLen;
        unsigned int framesize;
        file = fopen("cfg.bin","rb");
        newfile = fopen("ncfg.bin","wb");
        if (file != NULL) {
                //Get file length
                fseek(file, 0, SEEK_END);
                fileLen = ftell(file);
                fseek(file, 0, SEEK_SET);
                fprintf(fp_log,"File len %ld\n",fileLen);
                while (fileLen != 0) /* Till the EOF */{
                        fseek (file,2 ,SEEK_CUR);
                        fread(frame_len, sizeof(unsigned char),2, file);
                        fseek (file,-4 ,SEEK_CUR);
                        framesize = to_intconvertor(frame_len);
                        line = malloc(framesize*sizeof(unsigned char));
                        memset(line,'\0',sizeof(line));
                        fread(line, sizeof(unsigned char),framesize,file);
                        s = line;
                        s += 4;
                        //match IDCODE in cfg.bin file
                        copy_cbyc (id,s,2);
                        id[2] = '\0';
                        if(!ncmp_cbyc(id,idcode,2)) {
                                fprintf(fp_log,"MATCHED the IDCODE  file cfg.bin\n");
                                break;
                        } else {
                                //Place rest of lines in the new file
                                fwrite(line, sizeof(unsigned char),framesize,newfile);
                                free(line);
                                fileLen -= framesize;
                        }
                  }//While ends
                  fileLen -= framesize;
                  // If cfg.bin file still contains data copy it to ncfg.bin
                  while (fileLen != 0) /* Till the EOF */{
                        fseek (file,2 ,SEEK_CUR);
                        fread(frame_len, sizeof(unsigned char),2, file);
                        fseek (file,-4 ,SEEK_CUR);
                        framesize = to_intconvertor(frame_len);
                        line = malloc(framesize*sizeof(unsigned char));
                        memset(line,'\0',sizeof(line));
                        fread(line, sizeof(unsigned char),framesize,file);
                        fwrite(line, sizeof(unsigned char),framesize,newfile);
                        free(line);
                        fileLen -= framesize;
                  }
                //File renaming
                  fclose (file);
                  fclose(newfile);
                  if( remove( "cfg.bin" ) != 0 )
                      perror( "Error deleting file" );
                  result= rename("ncfg.bin","cfg.bin");
                  if ( result == 0 )
                      fputs ("File successfully renamed",fp_log);
                  else
                      perror( "Error renaming file" );
        } else {
                        perror ("cfg.bin"); /* why didn't the file open? */
        }
}
void* remove_llnode (void * temp)
Definition at line 638 of file new_pmu_or_pdc.c.
References cfgfirst, cfg_frame::cfgnext, fp_log, free_cfgframe_object(), cfg_frame::idcode, LLfirst, LLlast, mutex_cfg, mutex_file, mutex_Lower_Layer_Details, ncmp_cbyc(), Lower_Layer_Details::next, Lower_Layer_Details::pmuid, Lower_Layer_Details::prev, Lower_Layer_Details::protocol, remove_cfg_from_file(), Lower_Layer_Details::sockfd, and Lower_Layer_Details::thread_id.
Referenced by remove_Lower_Node().
{
        int rc,result;
        struct Lower_Layer_Details *temp_pmu = (struct Lower_Layer_Details *) temp;
        char pmuid[6];
        pthread_t tid = temp_pmu->thread_id;
        /* remove the entry from ipaddress.txt */
        FILE *fnew_ip = fopen("ipaddress1.txt","w");
        FILE *f_ip = fopen("ipaddress.txt","r");
        if (f_ip != NULL) {
                char s[40];
                memset(s,'\0',sizeof(s));
                while (fgets (s,sizeof(s),f_ip) != NULL) {
                         memset(pmuid,'\0',6);
                         sprintf(pmuid,"%d",temp_pmu->pmuid);
                         if((strstr(s,pmuid))&&(strstr(s,temp_pmu->protocol))) {
                                        break;
                        } else {
                        //Place rest of lines in the new file
                                fputs(s,fnew_ip);
                                memset(s,'\0',40);
                                memset(pmuid,'\0',6);
                        }
                  }//While ends
                  memset(s,'\0',sizeof(s));
                  // If ipaddress.txt file still contains data copy it to ipaddress1.txt
                  while (fgets (s, sizeof(s),f_ip) != NULL) /* read a line */{
                        fputs(s,fnew_ip);
                        memset(s,'\0',40);
                  }
                  fclose(f_ip);
                  fclose(fnew_ip);
                  if( remove( "ipaddress.txt" ) != 0 )
                      perror( "Error deleting file" );
                      result = rename("ipaddress1.txt","ipaddress.txt");
                  if ( result == 0 )
                      fputs ("File successfully renamed",fp_log);
                  else
                       perror("Error renaming file" );
        } else {
                perror("ipaddress.txt");
        }
        /* remove the cfg object from memory */
        int ind = 0,match = 0;
        struct cfg_frame *temp_cfg = cfgfirst,*tprev_cfg;
        unsigned char id_CODE[2];
        tprev_cfg = temp_cfg;
        id_CODE[0] = temp_pmu->pmuid >> 8;
        id_CODE[1] = temp_pmu->pmuid ;
        while(temp_cfg != NULL){
            if(!ncmp_cbyc(id_CODE,temp_cfg->idcode,2)) {
                match = 1;
                break;
             } else {
                ind++;
                tprev_cfg = temp_cfg;
                temp_cfg = temp_cfg->cfgnext;
             }
        }// While ends
        if(match) {
                pthread_mutex_lock(&mutex_cfg);
                if(!ind) {
                        // Replace the cfgfirst
                        cfgfirst = cfgfirst->cfgnext;
                        free_cfgframe_object(temp_cfg);
                        fprintf(fp_log,"Out of FIRST free_cfgframe_object()\n");
                        // Get the new value of the CFG frame
                        pthread_mutex_lock(&mutex_file);
                        remove_cfg_from_file(id_CODE);
                        pthread_mutex_unlock(&mutex_file);
                } else {
                        // Replace in between cfg
                        tprev_cfg->cfgnext = temp_cfg->cfgnext;
                        free_cfgframe_object(temp_cfg);
                        fprintf(fp_log,"Out of free_cfgframe_object()\n");
                        pthread_mutex_lock(&mutex_file);
                        remove_cfg_from_file(id_CODE);
                        pthread_mutex_unlock(&mutex_file);
                }
                pthread_mutex_unlock(&mutex_cfg);
        }
        pthread_mutex_lock(&mutex_Lower_Layer_Details); /* Remove the object from structure 'Lower Layer Details'*/
        if(temp_pmu->prev == NULL)  {
                LLfirst = temp_pmu->next;
                if(LLfirst != NULL)
                        LLfirst->prev = NULL;
        } else {
                if (temp_pmu == LLlast)
                        temp_pmu->prev->next = NULL;
                else
                        temp_pmu->prev->next = temp_pmu->next;
        }
        if(temp_pmu->next == NULL) {
                        LLlast = temp_pmu->prev;
        } else {
                if(temp_pmu->prev != NULL)
                        temp_pmu->prev->next = temp_pmu->next;
        }
        pthread_mutex_unlock(&mutex_Lower_Layer_Details);
        rc = pthread_cancel(tid);
        if(rc == 0)
                fprintf(fp_log,"Cancelled thread %ld\n",tid);
        close(temp_pmu->sockfd);                        /* Close the socket connection */
        free(temp_pmu);
        pthread_exit(NULL);
}
int remove_Lower_Node (char pmuid[], char protocol[])
Definition at line 539 of file new_pmu_or_pdc.c.
References Upper_Layer_Details::config_change, fp_log, Lower_Layer_Details::ip, LLfirst, mutex_Upper_Layer_Details, Upper_Layer_Details::next, Lower_Layer_Details::next, Lower_Layer_Details::pmuid, Lower_Layer_Details::port, Lower_Layer_Details::protocol, remove_llnode(), and ULfirst.
Referenced by cmd_or_remove_pmu_validation().
{
        int flag = 0, err;
        // A new thread is created for each TCP connection in 'detached' mode. Thus allowing any number of threads to be created.
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        if((err = pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED))) { // In  the detached state, the thread resources are
                                                                                // immediately freed when it terminates, but
                perror(strerror(err));                                          // pthread_join(3) cannot be used to synchronize
                exit(1);                                                        //  on the thread termination.
        }
        if((err = pthread_attr_setschedpolicy(&attr,SCHED_FIFO))) { // Shed policy = SCHED_FIFO (realtime, first-in first-out)
                perror(strerror(err));
                exit(1);
        }
        printf("####   Connection TABLE   ####\n");
        printf("-----------------------------------------------------------------\n");
        printf("|   PMU ID      |       IP      |       Port    |     Protocol  |\n");
        printf("-----------------------------------------------------------------\n");
        if(LLfirst == NULL) {
                printf("No PMU Added\n");
                return 1;
        } else {
                flag = 1;
                struct Lower_Layer_Details *t = LLfirst;
                while(t != NULL) {
                        printf("|\t%d\t|%s\t|\t%d\t|\t%s\t|\n",t->pmuid,t->ip,t->port,t->protocol);
                                t = t->next;
                }
                printf("-----------------------------------------------------------------\n");
        }
        if(flag) {
                int match = 0;
                struct Lower_Layer_Details *temp_pmu = LLfirst;
                while(temp_pmu != NULL) {
                        if((temp_pmu->pmuid == atoi(pmuid)) && (!strncasecmp(temp_pmu->protocol,protocol,3))) {
                                match = 1;
                                break;
                        } else {
                                temp_pmu = temp_pmu->next;
                        }
                }
                if(match) {
                        pthread_t t;
                        if((err = pthread_create(&t,&attr,remove_llnode,(void *)temp_pmu))) {
                                perror(strerror(err));
                                exit(1);
                        }
                        struct Upper_Layer_Details *temp_pdc = ULfirst;
                        pthread_mutex_lock(&mutex_Upper_Layer_Details);
                        while(temp_pdc != NULL ) {
                                temp_pdc->config_change = 1;
                                temp_pdc = temp_pdc->next;
                        }
                        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                        return 0;
                } else {
                        fprintf(fp_log,"No Match\n");
                        return 1;
                }
        }
        return 1;
}
int remove_PDC (char ip[], char port_num[], char protocol[])
Definition at line 1435 of file new_pmu_or_pdc.c.
References i, Upper_Layer_Details::ip, mutex_Upper_Layer_Details, Upper_Layer_Details::next, Upper_Layer_Details::port, Upper_Layer_Details::prev, Upper_Layer_Details::protocol, TCPPORT, UDPPORT, ULfirst, and ULlast.
Referenced by remove_pdc_validation().
{
        char *p,*i,*port;
        int flag = 0,result;
        if(ULfirst == NULL) {
                printf("No PDC Added\n");
                return 1;
        } else {
                struct Upper_Layer_Details *t = ULfirst;
                while(t != NULL) {
                        if(!strcmp(t->ip,ip)) {
                                if(((!strncasecmp(t->protocol,"UDP",3)) && (t->port == UDPPORT)) || ((!strncasecmp(t->protocol,"TCP",3)) && (t->port == TCPPORT))) {
                                        flag = 1;
                                        break;
                                }
                        }
                        t = t->next;
                }
                if(flag) {
                        pthread_mutex_lock(&mutex_Upper_Layer_Details);
                        if(t->prev == NULL)  {
                                ULfirst = t->next;
                                if(ULfirst != NULL) ULfirst->prev = NULL;
                        } else {
                                t->prev->next = t->next;
                        }
                        if(t->next == NULL) {
                                ULlast = t->prev;
                        } else {
                                if(t->prev != NULL)
                                t->prev->next = t->next;
                        }
                        free(t);
                        pthread_mutex_unlock(&mutex_Upper_Layer_Details);
                        FILE *fnew_ip = fopen("upperpdc_ip1.txt","w");
                        FILE *f_ip = fopen("upperpdc_ip.txt","r");
                        if (f_ip != NULL) {
                                flag = 0;
                                char s[40], s1[40];
                                memset(s,'\0',40);
                                memset(s1,'\0',40);
                                while (fgets (s, 40,f_ip) != NULL) {
                                strcpy(s1, s);
                                i = strtok (s," ");
                                port = strtok (NULL," ");
                                p = strtok (NULL," ");
                                if(!strcmp(i,ip) && (!strncasecmp(p,protocol,3))){
                                                flag = 1;
                                                printf("MATCH\n");
                                                break;
                                        } else {
                                                //Place rest of lines in the new file
                                                fputs(s1,fnew_ip);
                                                memset(s,'\0',40);
                                                memset(s1,'\0',40);
                                        }
                                  }//While ends
                                  memset(s,'\0',sizeof(s));
                                  // If ipaddress.txt file still contains data copy it to ipaddress1.txt
                                  while (fgets (s, sizeof(s),f_ip) != NULL) /* read a line */{
                                        fputs(s,fnew_ip);
                                        memset(s,'\0',40);
                                  }
                                  fclose(f_ip);
                                  fclose(fnew_ip);
                                  if( remove( "upperpdc_ip.txt" ) != 0 )
                                      perror( "Error deleting file" );
                                      result = rename("upperpdc_ip1.txt","upperpdc_ip.txt");
                                  if ( result != 0 )
                                       perror("Error renaming file" );
                                  return 0;
                        } else {
                                perror("upperpdc_ip.txt");
                                return 1;
                        }
                } else {
                        printf("\nNo Match\n");
                        return 1;
                }
        }
}