PMUSimulator: CfgGuiFunctions.c File Reference
CfgGuiFunctions.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <netinet/in.h>
#include <gtk/gtk.h>
#include "PmuGui.h"
#include "CfgFunction.h"
#include "CfgGuiFunctions.h"
Functions
int validation_cfg_create ()
int validation_phasor_names (GtkWidget *widget, gpointer udata)
int validation_analog_names (GtkWidget *widget, gpointer udata)
int validation_digital_names (GtkWidget *widget, gpointer udata)
int validation_ph_an_num (GtkButton *but, gpointer udata)
int validation_new_phasor_names (GtkWidget *widget, gpointer udata)
int validation_new_analog_names (GtkWidget *widget, gpointer udata)
int validation_new_data_rate (GtkButton *but, gpointer udata)
int validation_remove_ph_an_num (GtkButton *but, gpointer udata)
void validation_hdr_frm (GtkWidget *widget, gpointer udata)
void cfg_create_function (GtkWidget *widget, gpointer udata)
void channel_names_for_phasor ()
void channel_names_for_analog ()
void channel_names_for_digital ()
void final_cfg_create ()
void cfg_chng_options (GtkWidget *widget, gpointer udata)
void cfg_STAT_change (GtkWidget *widget, gpointer udata)
void Change_pmu_configuration (GtkWidget *widget, gpointer udata)
void new_phasor_num (GtkWidget *widget, gpointer udata)
void new_analog_num ()
void new_channel_names_for_phasor ()
void new_channel_names_for_analog ()
void change_data_rate_option ()
void enter_new_data_rate (GtkWidget *widget, gpointer udata)
void remove_phasor_num (GtkWidget *widget, gpointer udata)
void remove_analog_num ()
int final_cfg_update_call (GtkButton *but, gpointer udata)
void hdr_create_function (GtkWidget *widget, gpointer udata)
Function Documentation
void cfg_chng_options (GtkWidget * widget, gpointer udata)
Definition at line 1196 of file CfgGuiFunctions.c.
References CCOptionWin, cfg_STAT_change(), Change_pmu_configuration(), and markup.
Referenced by main().
        {
                /* local variables */
                GtkWidget *table, *label;
                GtkWidget *ID_butn, *PE_butn, *DS_butn;
                GtkWidget *PT_butn, *CC_butn, *close_butn;
                /* Create a new dialog window for the Configration Modification */
                CCOptionWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCOptionWin), "Configration Modification");
                gtk_container_set_border_width (GTK_CONTAINER (CCOptionWin), 10);
                gtk_widget_set_size_request (CCOptionWin, 400, 430);
                /* Create a table of 7 by 3 squares */
                table = gtk_table_new (9, 3, FALSE);
                /* Set the spacing to 15 on x and 60 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                gtk_table_set_col_spacings (GTK_TABLE (table), 60);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCOptionWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Change STAT Word</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                ID_butn = gtk_button_new_with_label ("Set Invalid Data bit");
                gtk_table_attach_defaults (GTK_TABLE (table), ID_butn, 1, 2, 2, 3);
                gtk_widget_show (ID_butn);
                PE_butn = gtk_button_new_with_label ("Set PMU Error bit");
                gtk_table_attach_defaults (GTK_TABLE (table), PE_butn, 1, 2, 3, 4);
                gtk_widget_show (PE_butn);
                DS_butn = gtk_button_new_with_label ("Set Data Sorting bit");
                gtk_table_attach_defaults (GTK_TABLE (table), DS_butn, 1, 2, 4, 5);
                gtk_widget_show (DS_butn);
                PT_butn = gtk_button_new_with_label ("Set PMU Trigger bit");
                gtk_table_attach_defaults (GTK_TABLE (table), PT_butn, 1, 2, 5, 6);
                gtk_widget_show (PT_butn);
                CC_butn = gtk_button_new_with_label ("Set Configuration Change bit");
                gtk_table_attach_defaults (GTK_TABLE (table), CC_butn, 1, 2, 6, 7);
                gtk_widget_show (CC_butn);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='8'><b>Note : The Synchronization error handle internaly.</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label,  1, 2, 8, 9);
                gtk_widget_show (label);
                g_free (markup);
                /* Add a "close" button to the bottom of the dialog */
                close_butn = gtk_button_new_with_label ("close");
                /* Signal handling for all buttons on Window */
                g_signal_connect (CC_butn, "clicked", G_CALLBACK (Change_pmu_configuration), NULL);
                g_signal_connect (ID_butn, "clicked", G_CALLBACK (cfg_STAT_change), (gpointer) "a");
                g_signal_connect (PE_butn, "clicked", G_CALLBACK (cfg_STAT_change), (gpointer) "b");
                g_signal_connect (DS_butn, "clicked", G_CALLBACK (cfg_STAT_change), (gpointer) "c");
                g_signal_connect (PT_butn, "clicked", G_CALLBACK (cfg_STAT_change), (gpointer) "d");
                g_signal_connect_swapped (close_butn, "clicked", G_CALLBACK (gtk_widget_destroy), CCOptionWin);
                g_signal_connect_swapped (CCOptionWin, "response", G_CALLBACK (gtk_widget_destroy), CCOptionWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (close_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCOptionWin)->action_area), close_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (close_butn);
                gtk_widget_show (close_butn);
                /* Finally show the CCOptionWin */
                gtk_widget_show (CCOptionWin);
        };
void cfg_create_function (GtkWidget * widget, gpointer udata)
Definition at line 715 of file CfgGuiFunctions.c.
References cfg_setup_window, markup, p_af, p_anNumber, p_dgNumber, p_drate, p_ff, p_id, p_pf, p_phNumber, p_pn, p_stn, Pmu_Help(), and validation_cfg_create().
Referenced by main().
        {
                /* local variables */
                GtkWidget *table, *label;
                GtkWidget *valdbutton, *help_button;
                /* Create a new dialog window for the PMU Configuration Setup window */
                cfg_setup_window = gtk_dialog_new ();
                g_signal_connect (cfg_setup_window, "destroy", G_CALLBACK (gtk_widget_destroy), cfg_setup_window);
                gtk_window_set_title (GTK_WINDOW (cfg_setup_window), "PMU Configuration Setup");
                gtk_container_set_border_width (GTK_CONTAINER (cfg_setup_window), 10);
                gtk_widget_set_size_request (cfg_setup_window, 350, 480);
                /* Create a table of 11 by 2 squares. */
                table = gtk_table_new (11, 2, FALSE);
                /* Set the spacing to 10 on x and 25 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 10);
                gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(cfg_setup_window)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                /* Add few buttons to the bottom of the dialog */
                valdbutton = gtk_button_new_with_label ("Next");
                help_button = gtk_button_new_with_label ("Help");
                /* This simply creates a grid of toggle buttons on the table */
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter PMU Configuration Details</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                label = gtk_label_new ("PMU ID                 ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 1, 2);
                gtk_widget_show (label);
                label = gtk_label_new ("Station Name         ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 2, 3);
                gtk_widget_show (label);
                label = gtk_label_new ("Frequency Format  ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 3, 4);
                gtk_widget_show (label);
                label = gtk_label_new ("Analog Format         ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 4, 5);
                gtk_widget_show (label);
                label = gtk_label_new ("Phasor Format         ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 5, 6);
                gtk_widget_show (label);
                label = gtk_label_new ("Phasor Notation       ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 6, 7);
                gtk_widget_show (label);
                label = gtk_label_new ("Number of Phasors    ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 7, 8);
                gtk_widget_show (label);
                label = gtk_label_new ("Number of Analog     ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 8, 9);
                gtk_widget_show (label);
                label = gtk_label_new ("Digital Status Word   ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 9, 10);
                gtk_widget_show (label);
                label = gtk_label_new ("Data Rate               ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 10, 11);
                gtk_widget_show (label);
                /* Create text boxes for user to enter appropriate values */
                p_id = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_id, 5);
                gtk_table_attach_defaults (GTK_TABLE (table), p_id, 1, 2, 1, 2);
                gtk_widget_show (p_id);
                /* Create combo boxe for user with some fixed values */
                p_stn = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_stn, 16);
                gtk_table_attach_defaults (GTK_TABLE (table), p_stn, 1, 2, 2, 3);
                gtk_widget_show (p_stn);
                p_ff = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_ff), "Fix Point");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_ff), "Floating Point");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_ff), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_ff, 1, 2, 3, 4);
                gtk_widget_show (p_ff);
                p_af = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_af), "Fix Point");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_af), "Floating Point");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_af), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_af, 1, 2, 4, 5);
                gtk_widget_show (p_af);
                p_pf = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_pf), "Fix Point");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_pf), "Floating Point");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_pf), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_pf, 1, 2, 5, 6);
                gtk_widget_show (p_pf);
                p_pn = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_pn), "Ractangular");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_pn), "Polar");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_pn), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_pn, 1, 2, 6, 7);
                gtk_widget_show (p_pn);
                p_phNumber = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_phNumber, 2);
                gtk_table_attach_defaults (GTK_TABLE (table), p_phNumber, 1, 2, 7, 8);
                gtk_widget_show (p_phNumber);
                p_anNumber = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_anNumber, 2);
                gtk_table_attach_defaults (GTK_TABLE (table), p_anNumber, 1, 2, 8, 9);
                gtk_widget_show (p_anNumber);
                p_dgNumber = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_dgNumber, 1);
                gtk_table_attach_defaults (GTK_TABLE (table), p_dgNumber, 1, 2, 9, 10);
                gtk_widget_show (p_dgNumber);
                p_drate = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "10");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "25");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "50");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "60");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_drate), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_drate, 1, 2, 10, 11);
                gtk_widget_show (p_drate);
                /* Signal handling for buttons on CFG Setuo Window */
                g_signal_connect_swapped (valdbutton, "clicked", G_CALLBACK (validation_cfg_create), valdbutton);
                g_signal_connect_swapped (help_button, "clicked", G_CALLBACK (Pmu_Help), NULL);
                g_signal_connect_swapped (cfg_setup_window, "destroy", G_CALLBACK (gtk_widget_destroy), cfg_setup_window);
                /* This makes it so the button is the default. */
                gtk_widget_set_can_default (valdbutton, TRUE);
                gtk_widget_set_can_default (help_button, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (cfg_setup_window)->action_area), valdbutton, TRUE, TRUE, 0);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (cfg_setup_window)->action_area), help_button, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (valdbutton);
                gtk_widget_show (valdbutton);
                gtk_widget_grab_default (help_button);
                gtk_widget_show (help_button);
                /* Finally show the cfg_setup_window */
                gtk_widget_show (cfg_setup_window);
        };
void cfg_STAT_change (GtkWidget * widget, gpointer udata)
Definition at line 1284 of file CfgGuiFunctions.c.
References CCOptionWin, and validation_result().
Referenced by cfg_chng_options().
        {
                /* local variables */
                char find_butn[2];
                static const char filename_1[] = "change.bin";
                FILE *file_1;
                /* For identifing singnal came from which button? */
                strcpy(find_butn,(char *) udata);
                if(!strcmp(find_butn, "a"))
                {
                        file_1 = fopen (filename_1,"w");
{
                                fprintf(file_1, "%s", "1");
                        }
                        fclose (file_1);
                        validation_result("\nSTAT CHANGED\n\nBit 15 of Stat word has been set to 1 for Invalid Data.\t\n");     /* Show the success message to user */
                }
                else if(!strcmp(find_butn, "b"))
                {
                        file_1 = fopen (filename_1,"w");
{
                                fprintf(file_1, "%s", "2");
                        }
                        fclose (file_1);
                        validation_result("\nSTAT CHANGED\n\n\nBit 14 of Stat word has been set to 1 for PMU Error.\n");        /* Show the success message to user */
                }
                else if(!strcmp(find_butn, "c"))
                {
                        file_1 = fopen (filename_1,"w");
{
                                fprintf(file_1, "%s", "3");
                        }
                        fclose (file_1);
                        validation_result("\nSTAT CHANGED\n\n\nBit 12 of Stat word has been set to 1 for Data Sorting.\n");     /* Show the success message to user */
                }
                else if(!strcmp(find_butn, "d"))
                {
                        file_1 = fopen (filename_1,"w");
{
                                fprintf(file_1, "%s", "4");
                        }
                        fclose (file_1);
                        validation_result("\nSTAT CHANGED\n\n\nBit 11 of Stat word has been set to 1 for PMU Trigger Detected.\n");     /* Show the success message to user */
                }
                /* Close/destroy the CCOptionWin */
                gtk_widget_destroy(CCOptionWin);
        };
void change_data_rate_option ()
Definition at line 1751 of file CfgGuiFunctions.c.
References CCWin, enter_new_data_rate(), final_cfg_update_call(), and markup.
Referenced by new_channel_names_for_analog(), validation_new_analog_names(), and validation_remove_ph_an_num().
        {
                /* local variables */
                GtkWidget *table;
                GtkWidget *Addbutton, *Removebutton;
                GtkWidget *close_butn, *label;
                /* Create a new dialog window for PMU Data Rate */
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "PMU Data Rate ");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 350);
                /* Create a table of 4 by 2 squares. */
                table = gtk_table_new (4, 2, FALSE);
                /* Set the spacing to 15 on x and 25 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Data Rate Options</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Add two radio buttons on the dialog window */
                Addbutton = gtk_radio_button_new_with_label (NULL, "YES");
                gtk_table_attach_defaults (GTK_TABLE (table), Addbutton, 0, 1, 2, 3);
                gtk_widget_show (Addbutton);
                Removebutton = gtk_radio_button_new_with_label (NULL, "NO");
                gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (Removebutton), TRUE);
                gtk_table_attach_defaults (GTK_TABLE (table), Removebutton, 0, 1, 3, 4);
                gtk_widget_show (Removebutton);
                /* Add a "close" button to the bottom of the dialog */
                close_butn = gtk_button_new_with_label ("Close");
                /* Signal handling for buttons on Data rate Window */
                g_signal_connect_swapped (Addbutton, "clicked", G_CALLBACK (enter_new_data_rate), NULL);
                g_signal_connect_swapped (Removebutton, "clicked", G_CALLBACK (final_cfg_update_call), NULL);
                g_signal_connect_swapped (close_butn, "clicked", G_CALLBACK (gtk_widget_destroy), CCWin);
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (close_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), close_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (close_butn);
                gtk_widget_show (close_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void Change_pmu_configuration (GtkWidget * widget, gpointer udata)
Definition at line 1342 of file CfgGuiFunctions.c.
References CCOptionWin, CCWin, markup, new_phasor_num(), and remove_phasor_num().
Referenced by cfg_chng_options().
        {
                /* local variables */
                GtkWidget *table;
                GtkWidget *close_butn, *label;
                GtkWidget *Addbutton, *Removebutton;
                /* Create a new dialog window for the Option Window */
                gtk_widget_destroy(CCOptionWin);
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "Option Window");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 350);
                /* Create a table of 4 by 2 squares */
                table = gtk_table_new (4, 2, FALSE);
                /* Set the spacing to 15 on x and 25 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Select Appropriate Option</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Add few radio buttons on the dialog window */
                Addbutton = gtk_radio_button_new_with_label (NULL, "Add New Channels");
                gtk_table_attach_defaults (GTK_TABLE (table), Addbutton, 0, 1, 2, 3);
                gtk_widget_show (Addbutton);
                Removebutton = gtk_radio_button_new_with_label (NULL, "Remove Channels");
                gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (Removebutton), TRUE);
                gtk_table_attach_defaults (GTK_TABLE (table), Removebutton, 0, 1, 3, 4);
                gtk_widget_show (Removebutton);
                /* Add 'Close' buttons on the dialog window */
                close_butn = gtk_button_new_with_label ("Close");
                /* Signal handling for buttons on Option Window */
                g_signal_connect_swapped (Addbutton, "clicked", G_CALLBACK (new_phasor_num), NULL);
                g_signal_connect_swapped (Removebutton, "clicked", G_CALLBACK (remove_phasor_num), NULL);
                g_signal_connect_swapped (close_butn, "clicked", G_CALLBACK (gtk_widget_destroy), CCWin);
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default. */
                gtk_widget_set_can_default (close_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), close_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (close_butn);
                gtk_widget_show (close_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void channel_names_for_analog ()
Definition at line 969 of file CfgGuiFunctions.c.
References AnalogChWin, ConfigurationFrame::cfg_annmr_val, cfg_info, channel_names_for_digital(), i, markup, num_text, and validation_analog_names().
Referenced by validation_phasor_names().
        {
                /* Analog is not Mandatory component in CFG, it could be zero */
                if (cfg_info->cfg_annmr_val == 0)
                {
                        /* Next call to digital channel names */
                        channel_names_for_digital ();
                }
                else    /* if ANNMR > 0 */
                {
                        /* local variables */
                        int i;
                        char line[30];
                        GtkWidget *table, *scrolled_window;
                        GtkWidget *label, *next_button;
                        /* Create a new dialog window for the scrolled window to be packed into */
                        AnalogChWin = gtk_dialog_new ();
                        g_signal_connect (AnalogChWin, "destroy", G_CALLBACK (gtk_widget_destroy), AnalogChWin);
                        gtk_window_set_title (GTK_WINDOW (AnalogChWin), "Analog Channels");
                        gtk_container_set_border_width (GTK_CONTAINER (AnalogChWin), 10);
                        gtk_widget_set_size_request (AnalogChWin, 400, 350);
                        /* Create a new scrolled window */
                        scrolled_window = gtk_scrolled_window_new (NULL, NULL);
                        gtk_container_set_border_width (GTK_CONTAINER (scrolled_window), 10);
                        /* The policy is one of GTK_POLICY AUTOMATIC, or GTK_POLICY_ALWAYS. GTK_POLICY_AUTOMATIC will automatically decide whether you need scrollbars,
                           whereas GTK_POLICY_ALWAYS will always leave the scrollbars there. The first one is the horizontal scrollbar, the second is vertical. */
                        gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
                        /* The dialog window is created with a vbox packed into it */
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG(AnalogChWin)->vbox), scrolled_window, TRUE, TRUE, 0);
                        gtk_widget_show (scrolled_window);
                        /* Create a table of ? by 2 squares */
                        table = gtk_table_new (cfg_info->cfg_annmr_val+1, 2, FALSE);
                        label = gtk_label_new (" ");
                        markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='10'><b>Enter Analog Channels Name</b></span>");
                        gtk_label_set_markup (GTK_LABEL (label), markup);
                        gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                        gtk_widget_show (label);
                        g_free (markup);
                        /* Set the spacing to 15 on x and 25 on y */
                        gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                        gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                        /* Pack the table into the window */
                        gtk_scrolled_window_add_with_viewport (GTK_SCROLLED_WINDOW (scrolled_window), table);
                        gtk_widget_show (table);
                        /* Add a "Next" button to the bottom of the dialog */
                        next_button = gtk_button_new_with_label ("Next");
                        /* This simply creates a grid of Lables with text on the table to demonstrate the scrolled window. */
                        for(i=1; i<cfg_info->cfg_annmr_val+1; i++)
{
                                memset(line,'\0',sizeof(line));
                                sprintf(line, "Analog Channel %d : ", i);
                                label = gtk_label_new (line);
                                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, i, i+1);
                                gtk_widget_show (label);
                        }
                        for(i=1; i<cfg_info->cfg_annmr_val+1; i++)
{
                                num_text[i] = gtk_entry_new ();
                                gtk_entry_set_max_length ((GtkEntry *)num_text[i], 16);
                                gtk_table_attach_defaults (GTK_TABLE (table), num_text[i], 1, 2, i, i+1);
                                gtk_widget_show (num_text[i]);
                        }
                        /* Signal handling for Next button on Window */
                        g_signal_connect_swapped (next_button, "clicked", G_CALLBACK (validation_analog_names), NULL);
                        /* This makes it so the button is the default. */
                        gtk_widget_set_can_default (next_button, TRUE);
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG (AnalogChWin)->action_area), next_button, TRUE, TRUE, 0);
                        /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                        gtk_widget_grab_default (next_button);
                        gtk_widget_show (next_button);
                        /* Finally show the AnalogChWin */
                        gtk_widget_show (AnalogChWin);
                }
        };
void channel_names_for_digital ()
Definition at line 1065 of file CfgGuiFunctions.c.
References AnalogChWin, ConfigurationFrame::cfg_dgnmr_val, cfg_info, final_cfg_create(), i, markup, num_text, and validation_digital_names().
Referenced by channel_names_for_analog(), and validation_analog_names().
        {
                /* Analog is not Mandatory component in CFG, it could be zero */
                if (cfg_info->cfg_dgnmr_val == 0)
                {
                        /* Next call to 'final_cfg_create ()' */
                        final_cfg_create ();
                }
                else    /* if DGNMR > 0 */
                {
                        /* local variables */
                        int i;
                        char line[30];
                        GtkWidget *table, *scrolled_window;
                        GtkWidget *label, *next_button;
                        /* Create a new dialog window for the scrolled window to be packed into */
                        AnalogChWin = gtk_dialog_new ();
                        g_signal_connect (AnalogChWin, "destroy", G_CALLBACK (gtk_widget_destroy), AnalogChWin);
                        gtk_window_set_title (GTK_WINDOW (AnalogChWin), "Digital Channels");
                        gtk_container_set_border_width (GTK_CONTAINER (AnalogChWin), 10);
                        gtk_widget_set_size_request (AnalogChWin, 400, 550);
                        /* Create a new scrolled window */
                        scrolled_window = gtk_scrolled_window_new (NULL, NULL);
                        gtk_container_set_border_width (GTK_CONTAINER (scrolled_window), 10);
                        gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
                        /* The dialog window is created with a vbox packed into it */
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG(AnalogChWin)->vbox), scrolled_window, TRUE, TRUE, 0);
                        gtk_widget_show (scrolled_window);
                        /* Create a table of ? by 2 squares. */
                        table = gtk_table_new (cfg_info->cfg_dgnmr_val*16+1, 2, FALSE);
                        /* Set the spacing to 15 on x and 25 on y */
                        gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                        gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                        /* Pack the table into the window */
                        gtk_scrolled_window_add_with_viewport (GTK_SCROLLED_WINDOW (scrolled_window), table);
                        gtk_widget_show (table);
                        /* Add a "Next" button to the bottom of the dialog */
                        next_button = gtk_button_new_with_label ("Next");
                        label = gtk_label_new (" ");
                        markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='10'><b>Enter Digital Channels Name</b></span>");
                        gtk_label_set_markup (GTK_LABEL (label), markup);
                        gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                        gtk_widget_show (label);
                        g_free (markup);
                        /* This simply creates a grid of Lables with text on the table to demonstrate the scrolled window. */
                        for(i=1; i<cfg_info->cfg_dgnmr_val*16+1; i++)
{
                                memset(line,'\0',sizeof(line));
                                sprintf(line, "Digita Channel %d : ", i);
                                label = gtk_label_new (line);
                                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, i, i+1);
                                gtk_widget_show (label);
                        }
                        for(i=1; i<cfg_info->cfg_dgnmr_val*16+1; i++)
{
                                num_text[i] = gtk_entry_new ();
                                //gtk_entry_set_max_length (GtkEntry *entry, gint max);
                                gtk_entry_set_max_length ((GtkEntry *)num_text[i], 16);
                                gtk_table_attach_defaults (GTK_TABLE (table), num_text[i], 1, 2, i, i+1);
                                gtk_widget_show (num_text[i]);
                        }
                        /* Signal handling for Next button on Window */
                        g_signal_connect_swapped (next_button, "clicked", G_CALLBACK (validation_digital_names), NULL);
                        /* This makes it so the button is the default. */
                        gtk_widget_set_can_default (next_button, TRUE);
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG (AnalogChWin)->action_area), next_button, TRUE, TRUE, 0);
                        /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                        gtk_widget_grab_default (next_button);
                        gtk_widget_show (next_button);
                        /* Finally show the AnalogChWin */
                        gtk_widget_show (AnalogChWin);
                }
        };
void channel_names_for_phasor ()
Definition at line 882 of file CfgGuiFunctions.c.
References cfg_info, ConfigurationFrame::cfg_phnmr_val, i, markup, num_text, PhasorChWin, and validation_phasor_names().
Referenced by validation_cfg_create().
        {
                /* local variables */
                int i;
                char line[20];
                GtkWidget *table, *scrolled_window;
                GtkWidget *label, *next_button;
                /* Create a new dialog window for the scrolled window to be packed into */
                PhasorChWin = gtk_dialog_new ();
                g_signal_connect (PhasorChWin, "destroy", G_CALLBACK (gtk_widget_destroy), PhasorChWin);
                gtk_window_set_title (GTK_WINDOW (PhasorChWin), "Phasor Channels");
                gtk_container_set_border_width (GTK_CONTAINER (PhasorChWin), 10);
                gtk_widget_set_size_request (PhasorChWin, 400, 400);
                /* Create a new scrolled window */
                scrolled_window = gtk_scrolled_window_new (NULL, NULL);
                gtk_container_set_border_width (GTK_CONTAINER (scrolled_window), 10);
                /* The policy is one of GTK_POLICY AUTOMATIC, or GTK_POLICY_ALWAYS. GTK_POLICY_AUTOMATIC will automatically decide whether you need scrollbars,
                   whereas GTK_POLICY_ALWAYS will always leave the scrollbars there. The first one is the horizontal scrollbar, the second is vertical. */
                gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
                /* The dialog window is created with a vbox packed into it */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(PhasorChWin)->vbox), scrolled_window, TRUE, TRUE, 0);
                gtk_widget_show (scrolled_window);
                /* Create a table of ? by 2 squares. */
                table = gtk_table_new (cfg_info->cfg_phnmr_val+1, 2, FALSE);
                /* Set the spacing to 15 on x and 25 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 15);
                gtk_table_set_col_spacings (GTK_TABLE (table), 25);
                /* Pack the table into the window */
                gtk_scrolled_window_add_with_viewport (GTK_SCROLLED_WINDOW (scrolled_window), table);
                gtk_widget_show (table);
                /* Add a "Next" button to the bottom of the dialog */
                next_button = gtk_button_new_with_label ("Next");
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='10'><b>Enter Phasor Channels Name</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* This simply creates a grid of Lables with text on the table to demonstrate the scrolled window. */
                for(i=1; i<cfg_info->cfg_phnmr_val+1; i++)
                {
                        memset(line,'\0',sizeof(line));
                        sprintf(line, "Phasor Channel %d : ", i);
                        label = gtk_label_new (line);
                        gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, i, i+1);
                        gtk_widget_show (label);
                }
                for(i=1; i<cfg_info->cfg_phnmr_val+1; i++)
                {
                        num_text[i] = gtk_entry_new ();
                        gtk_entry_set_max_length ((GtkEntry *)num_text[i], 16);
                        gtk_table_attach_defaults (GTK_TABLE (table), num_text[i], 1, 2, i, i+1);
                        gtk_widget_show (num_text[i]);
                }
                /* Signal handling for Next button on Window */
                g_signal_connect_swapped (next_button, "clicked", G_CALLBACK (validation_phasor_names), NULL);
                /* This makes it so the button is the default. */
                gtk_widget_set_can_default (next_button, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (PhasorChWin)->action_area), next_button, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_button);
                gtk_widget_show (next_button);
                /* Finally show the PhasorChWin */
                gtk_widget_show (PhasorChWin);
        };
void enter_new_data_rate (GtkWidget * widget, gpointer udata)
Definition at line 1820 of file CfgGuiFunctions.c.
References CCWin, markup, p_drate, and validation_new_data_rate().
Referenced by change_data_rate_option().
        {
                /* local variables */
                GtkWidget *table;
                GtkWidget *next_butn, *label;
                /* Create a new dialog window for the New Data Rate */
                gtk_widget_destroy(CCWin);
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "New Data Rate");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 300);
                /* Create a table of 3 by 3 squares */
                table = gtk_table_new (3, 3, FALSE);
                /* Set the spacing to 25 on x and 40 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 25);
                gtk_table_set_col_spacings (GTK_TABLE (table), 40);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b> Select Data Rate</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create combo boxe for user with some fixed values */
                p_drate = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "10");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "25");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "50");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_drate), "60");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_drate), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_drate, 1, 2, 1, 2);
                gtk_widget_show (p_drate);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='8'><b>Note : The data frame sends according to new\n\t  data rate.</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 2, 3);
                gtk_widget_show (label);
                g_free (markup);
                /* Add a "next" button to the bottom of the dialog */
                next_butn = gtk_button_new_with_label ("Next");
                /* Signal handling for buttons on Data Rate Window */
                g_signal_connect (next_butn, "clicked", G_CALLBACK (validation_new_data_rate), NULL);
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (next_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), next_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_butn);
                gtk_widget_show (next_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void final_cfg_create ()
Definition at line 1160 of file CfgGuiFunctions.c.
References _pmuStruct::cfg_modification_button, create_cfg(), _pmuStruct::create_cfg_button, _pmuStruct::header_frm_button, pmu_data, _pmuStruct::pmu_details_button, and validation_result().
Referenced by channel_names_for_digital(), and validation_digital_names().
        {
                /* local variables */
                int ret_val;
                char *display_msg;
                /* To create CFG call 'create_cfg()' */
                ret_val = create_cfg();
                if(ret_val == 0)
                {
                        /* Enable rest of the buttons on PMU Simulator Window */
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->header_frm_button), TRUE);
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->pmu_details_button), TRUE);
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->cfg_modification_button), TRUE);
                        /* Disable create CFG buttons on PMU Simulator Window */
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->create_cfg_button), FALSE);
                        display_msg = "\tConfiguration Frame for PMU successfully made\t\n";
                        validation_result (display_msg);        /* Show the success message to user */
                }
                else
                {
                        display_msg = "\t\tConfiguration Frame for PMU failed.\t\t\n\t\t\t\tPlease try again\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                }
        };
int final_cfg_update_call (GtkButton * but, gpointer udata)
Definition at line 2047 of file CfgGuiFunctions.c.
References CCWin, ConfigurationChange::data_rate_choice, new_cfg_info, ConfigurationChange::new_data_rate, and reconfig_cfg_CC().
Referenced by change_data_rate_option().
        {
                new_cfg_info->data_rate_choice = 0;
                new_cfg_info->new_data_rate = 0;
                /* Close/destroy the CCWin */
                gtk_widget_destroy(CCWin);
                /* Final call to recreate configuration frame */
                reconfig_cfg_CC();
                return 0;
        };
void hdr_create_function (GtkWidget * widget, gpointer udata)
Definition at line 2068 of file CfgGuiFunctions.c.
References CCWin, HdrFrm, markup, and validation_hdr_frm().
Referenced by main().
        {
                /* local variables */
                GtkWidget *table, *label;
                GtkWidget *close_butn, *vald_butn;
                /* Create a new dialog window for the Header Frame Window */
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "Header Frame");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 500, 350);
                /* Create a table of 3 by 2 squares */
                table = gtk_table_new (3, 2, FALSE);
                /* Set the spacing to 30 on x */
                gtk_table_set_row_spacings (GTK_TABLE (table), 30);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter Header Frame Details</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create text boxes for user to enter appropriate values */
                HdrFrm = gtk_entry_new();
                gtk_table_attach_defaults (GTK_TABLE (table), HdrFrm, 0, 1, 1, 2);
                gtk_widget_show (HdrFrm);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='8'><b>Note : Header frame includes the information about the PMU, the data sources,\n\t  scaling, algorithms, filtering, or other related information.</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 2, 3);
                gtk_widget_show (label);
                g_free (markup);
                /* Add few buttons at the bottom of the dialog */
                vald_butn = gtk_button_new_with_label ("Create");
                close_butn = gtk_button_new_with_label ("Close");
                /* Signal handling for buttons on Window */
                g_signal_connect (vald_butn, "clicked", G_CALLBACK (validation_hdr_frm), (gpointer) "2");
                g_signal_connect_swapped (close_butn, "clicked", G_CALLBACK (gtk_widget_destroy), CCWin);
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (vald_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), vald_butn, TRUE, TRUE, 0);
                gtk_widget_set_can_default (close_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), close_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (vald_butn);
                gtk_widget_show (vald_butn);
                gtk_widget_grab_default (close_butn);
                gtk_widget_show (close_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void new_analog_num ()
Definition at line 1483 of file CfgGuiFunctions.c.
References CCWin, markup, phtext, and validation_ph_an_num().
Referenced by new_channel_names_for_phasor(), and validation_new_phasor_names().
        {
                /* local variables */
                GtkWidget *table;
                GtkWidget *next_butn, *label;
                /* Create a new dialog window for the New Analog Channels */
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "New Analog Channels");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 300);
                /* Create a table of 3 by 3 squares */
                table = gtk_table_new (3, 3, FALSE);
                /* Set the spacing to 25 on x and 40 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 25);
                gtk_table_set_col_spacings (GTK_TABLE (table), 40);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b> Enter number of new Analogs</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create text boxes for user to enter appropriate values */
                phtext = gtk_entry_new ();
                gtk_table_attach_defaults (GTK_TABLE (table), phtext, 1, 2, 1, 2);
                gtk_widget_show (phtext);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='8'><b>Note : The new analog channels will be added to\n\t  existing configuration frame.</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 2, 3);
                gtk_widget_show (label);
                g_free (markup);
                /* Add a "Next" button to the bottom of the dialog */
                next_butn = gtk_button_new_with_label ("Next");
                /* Signal handling for buttons on Window */
                g_signal_connect (next_butn, "clicked", G_CALLBACK (validation_ph_an_num), (gpointer) "2");
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default. */
                gtk_widget_set_can_default (next_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), next_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_butn);
                gtk_widget_show (next_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void new_channel_names_for_analog ()
Definition at line 1651 of file CfgGuiFunctions.c.
References CCWin, change_data_rate_option(), i, markup, ConfigurationChange::new_cfg_annmr_val, new_cfg_info, num_text, PhasorChWin, and validation_new_analog_names().
Referenced by validation_ph_an_num().
        {
                /* new_analog number could be zero? */
                if(new_cfg_info->new_cfg_annmr_val > 0)
                {
                        /* local variables */
                        int i;
                        char line[30];
                        GtkWidget *table, *scrolled_window;
                        GtkWidget *label, *next_button;
                        /* Create a new dialog window for the scrolled window to be packed into */
                        gtk_widget_destroy(CCWin);
                        PhasorChWin = gtk_dialog_new ();
                        g_signal_connect (PhasorChWin, "destroy", G_CALLBACK (gtk_widget_destroy), PhasorChWin);
                        gtk_window_set_title (GTK_WINDOW (PhasorChWin), "New Analog Channels");
                        gtk_container_set_border_width (GTK_CONTAINER (PhasorChWin), 10);
                        gtk_widget_set_size_request (PhasorChWin, 420, 350);
                        /* Create a new scrolled window */
                        scrolled_window = gtk_scrolled_window_new (NULL, NULL);
                        gtk_container_set_border_width (GTK_CONTAINER (scrolled_window), 10);
                        /* The policy is one of GTK_POLICY AUTOMATIC, or GTK_POLICY_ALWAYS. GTK_POLICY_AUTOMATIC will automatically decide whether you need scrollbars,
                           whereas GTK_POLICY_ALWAYS will always leave the scrollbars there. The first one is the horizontal scrollbar, the second is vertical */
                        gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
                        /* The dialog window is created with a vbox packed into it */
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG(PhasorChWin)->vbox), scrolled_window, TRUE, TRUE, 0);
                        gtk_widget_show (scrolled_window);
                        /* Create a table of ? by 2 squares */
                        table = gtk_table_new (new_cfg_info->new_cfg_annmr_val+1, 2, FALSE);
                        /* Set the spacing to 10 on x and 30 on y */
                        gtk_table_set_row_spacings (GTK_TABLE (table), 10);
                        gtk_table_set_col_spacings (GTK_TABLE (table), 30);
                        /* Pack the table into the window */
                        gtk_scrolled_window_add_with_viewport (GTK_SCROLLED_WINDOW (scrolled_window), table);
                        gtk_widget_show (table);
                        /* Add a "next" button to the bottom of the dialog */
                        next_button = gtk_button_new_with_label ("Next");
                        label = gtk_label_new (" ");
                        markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter New Analog Channel Names</b></span>");
                        gtk_label_set_markup (GTK_LABEL (label), markup);
                        gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                        gtk_widget_show (label);
                        g_free (markup);
                        /* This simply creates a grid of Lables with text on the table to demonstrate the scrolled window */
                        for(i=1; i<new_cfg_info->new_cfg_annmr_val+1; i++)
{
                                memset(line,'\0',sizeof(line));
                                sprintf(line, "New Analog Channel %d : ", i);
                                label = gtk_label_new (line);
                                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, i, i+1);
                                gtk_widget_show (label);
                        }
                        for(i=1; i<new_cfg_info->new_cfg_annmr_val+1; i++)
{
                                num_text[i] = gtk_entry_new ();
                                gtk_entry_set_max_length ((GtkEntry *)num_text[i], 16);
                                gtk_table_attach_defaults (GTK_TABLE (table), num_text[i], 1, 2, i, i+1);
                                gtk_widget_show (num_text[i]);
                        }
                        /* Signal handling for Next button on Window */
                        g_signal_connect_swapped (next_button, "clicked", G_CALLBACK (validation_new_analog_names), NULL);
                        /* This makes it so the button is the default */
                        gtk_widget_set_can_default (next_button, TRUE);
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG (PhasorChWin)->action_area), next_button, TRUE, TRUE, 0);
                        /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                        gtk_widget_grab_default (next_button);
                        gtk_widget_show (next_button);
                        /* Finally show the PhasorChWin */
                        gtk_widget_show (PhasorChWin);
                }
                else    /* if new_phasor < 0 */
                {
                        /* Close/destroy the CCWin */
                        gtk_widget_destroy(CCWin);
                        /* Next call to data rate change option? */
                        change_data_rate_option();
                }
        };
void new_channel_names_for_phasor ()
Definition at line 1550 of file CfgGuiFunctions.c.
References CCWin, i, markup, new_analog_num(), new_cfg_info, ConfigurationChange::new_cfg_phnmr_val, num_text, PhasorChWin, and validation_new_phasor_names().
Referenced by validation_ph_an_num().
        {
                /* new_phasor number could be zero? */
                if(new_cfg_info->new_cfg_phnmr_val > 0)
                {
                        /* local variables */
                        int i;
                        char line[30];
                        GtkWidget *table, *scrolled_window;
                        GtkWidget *label, *next_button;
                        /* Create a new dialog window for the scrolled window to be packed into */
                        gtk_widget_destroy(CCWin);
                        PhasorChWin = gtk_dialog_new ();
                        g_signal_connect (PhasorChWin, "destroy", G_CALLBACK (gtk_widget_destroy), PhasorChWin);
                        gtk_window_set_title (GTK_WINDOW (PhasorChWin), "New Phasor");
                        gtk_container_set_border_width (GTK_CONTAINER (PhasorChWin), 10);
                        gtk_widget_set_size_request (PhasorChWin, 420, 350);
                        /* Create a new scrolled window */
                        scrolled_window = gtk_scrolled_window_new (NULL, NULL);
                        gtk_container_set_border_width (GTK_CONTAINER (scrolled_window), 10);
                        /* The policy is one of GTK_POLICY AUTOMATIC, or GTK_POLICY_ALWAYS. GTK_POLICY_AUTOMATIC will automatically decide whether you need scrollbars,
                           whereas GTK_POLICY_ALWAYS will always leave the scrollbars there. The first one is the horizontal scrollbar, the second is vertical */
                        gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolled_window), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
                        /* The dialog window is created with a vbox packed into it */
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG(PhasorChWin)->vbox), scrolled_window, TRUE, TRUE, 0);
                        gtk_widget_show (scrolled_window);
                        /* Create a table of ? by 2 squares */
                        table = gtk_table_new (new_cfg_info->new_cfg_phnmr_val+1, 2, FALSE);
                        /* Set the spacing to 10 on x and 30 on y */
                        gtk_table_set_row_spacings (GTK_TABLE (table), 10);
                        gtk_table_set_col_spacings (GTK_TABLE (table), 30);
                        /* Pack the table into the window */
                        gtk_scrolled_window_add_with_viewport (GTK_SCROLLED_WINDOW (scrolled_window), table);
                        gtk_widget_show (table);
                        /* Add a "next" button to the bottom of the dialog */
                        next_button = gtk_button_new_with_label ("Next");
                        label = gtk_label_new (" ");
                        markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter New Phasor Channel Names</b></span>");
                        gtk_label_set_markup (GTK_LABEL (label), markup);
                        gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                        gtk_widget_show (label);
                        g_free (markup);
                        /* This simply creates a grid of Lables with text on the table to demonstrate the scrolled window */
                        for(i=1; i<new_cfg_info->new_cfg_phnmr_val+1; i++)
{
                                memset(line,'\0',sizeof(line));
                                sprintf(line, "New Phasor Channel %d : ", i);
                                label = gtk_label_new (line);
                                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, i, i+1);
                                gtk_widget_show (label);
                        }
                        for(i=1; i<new_cfg_info->new_cfg_phnmr_val+1; i++)
{
                                num_text[i] = gtk_entry_new ();
                                gtk_entry_set_max_length ((GtkEntry *)num_text[i], 16);
                                gtk_table_attach_defaults (GTK_TABLE (table), num_text[i], 1, 2, i, i+1);
                                gtk_widget_show (num_text[i]);
                        }
                        /* Signal handling for Next button on Window */
                        g_signal_connect_swapped (next_button, "clicked", G_CALLBACK (validation_new_phasor_names), NULL);
                        /* This makes it so the button is the default */
                        gtk_widget_set_can_default (next_button, TRUE);
                        gtk_box_pack_start (GTK_BOX (GTK_DIALOG (PhasorChWin)->action_area), next_button, TRUE, TRUE, 0);
                        /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                        gtk_widget_grab_default (next_button);
                        gtk_widget_show (next_button);
                        /* Finally show the PhasorChWin */
                        gtk_widget_show (PhasorChWin);
                }
                else    /* if new_phasor < 0 */
                {
                        /* Close/destroy the CCWin */
                        gtk_widget_destroy(CCWin);
                        /* Next call to new analog numbers */
                        new_analog_num();
                }
        };
void new_phasor_num (GtkWidget * widget, gpointer udata)
Definition at line 1411 of file CfgGuiFunctions.c.
References ConfigurationChange::add_remove_choice, CCWin, markup, new_cfg_info, phtext, and validation_ph_an_num().
Referenced by Change_pmu_configuration().
        {
                /* local variables */
                GtkWidget *table;
                GtkWidget *next_butn, *label;
                /* Allocate the memory for the ConfigurationChange object */
                new_cfg_info = malloc(sizeof(struct ConfigurationChange));
                new_cfg_info->add_remove_choice = 1;
                /* Create a new dialog window for New Phasor Channels */
                gtk_widget_destroy(CCWin);
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "New Phasor Channels");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 300);
                /* Create a table of 3 by 3 squares. */
                table = gtk_table_new (3, 3, FALSE);
                /* Set the spacing to 25 on x and 40 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 25);
                gtk_table_set_col_spacings (GTK_TABLE (table), 40);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b> Enter number of new Phasors</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create text boxes for user to enter appropriate values */
                phtext = gtk_entry_new ();
                gtk_table_attach_defaults (GTK_TABLE (table), phtext, 1, 2, 1, 2);
                gtk_widget_show (phtext);
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='8'><b>Note : The new phasor channels will be added to\n\t  existing configuration frame.</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 2, 3);
                gtk_widget_show (label);
                g_free (markup);
                /* Add a "Next" button to the bottom of the dialog */
                next_butn = gtk_button_new_with_label ("Next");
                /* Signal handling for buttons on Window */
                g_signal_connect (next_butn, "clicked", G_CALLBACK (validation_ph_an_num), (gpointer) "1");
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (next_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), next_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_butn);
                gtk_widget_show (next_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void remove_analog_num ()
Definition at line 1972 of file CfgGuiFunctions.c.
References CCWin, ConfigurationFrame::cfg_annmr_val, cfg_info, markup, phtext, and validation_remove_ph_an_num().
Referenced by validation_remove_ph_an_num().
        {
                /* local variables */
                char line[50], buff[10];
                GtkWidget *table;
                GtkWidget *next_butn, *label;
                /* Close/destroy the CCWin */
                gtk_widget_destroy(CCWin);
                /* Create a new dialog window for the Remove Analog Window */
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "Remove Analog Window");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 300);
                /* Create a table of 5 by 3 squares */
                table = gtk_table_new (5, 3, FALSE);
                /* Set the spacing to 5 on x and 40 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 5);
                gtk_table_set_col_spacings (GTK_TABLE (table), 40);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                /* This simply creates a grid of Lables with text on the table */
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter Number of Analog</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 1, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create text boxes for user to enter appropriate values */
                phtext = gtk_entry_new ();
                gtk_table_attach_defaults (GTK_TABLE (table), phtext, 1, 2, 3, 4);
                gtk_widget_show (phtext);
                memset(line, '\0', 50);
                memset(buff, '\0', 10);
                strcat(line, "Note : Maximum Removal upto ");
                sprintf(buff,"%d",cfg_info->cfg_annmr_val);
                strcat(line, buff);
                strcat(line, "       ");
                label = gtk_label_new (line);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 1, 2, 4, 5);
                gtk_widget_show (label);
                /* Add a "next" button to the bottom of the dialog */
                next_butn = gtk_button_new_with_label ("Next");
                /* Signal handling for buttons on Window */
                g_signal_connect (next_butn, "clicked", G_CALLBACK (validation_remove_ph_an_num), (gpointer) "2");
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (next_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), next_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_butn);
                gtk_widget_show (next_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
void remove_phasor_num (GtkWidget * widget, gpointer udata)
Definition at line 1894 of file CfgGuiFunctions.c.
References ConfigurationChange::add_remove_choice, CCWin, cfg_info, ConfigurationFrame::cfg_phnmr_val, markup, new_cfg_info, phtext, and validation_remove_ph_an_num().
Referenced by Change_pmu_configuration().
        {
                /* local variables */
                char line[50], buff[10];
                GtkWidget *table;
                GtkWidget *next_butn, *label;
                /* Allocate the memory for the ConfigurationChange object */
                new_cfg_info = malloc(sizeof(struct ConfigurationChange));
                new_cfg_info->add_remove_choice = 2;
                /* Create a new dialog window for the Remove Phasor */
                gtk_widget_destroy(CCWin);
                CCWin = gtk_dialog_new ();
                gtk_window_set_title (GTK_WINDOW (CCWin), "Remove Phasor");
                gtk_container_set_border_width (GTK_CONTAINER (CCWin), 10);
                gtk_widget_set_size_request (CCWin, 350, 300);
                /* Create a table of 5 by 3 squares */
                table = gtk_table_new (5, 3, FALSE);
                /* Set the spacing to 5 on x and 40 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 5);
                gtk_table_set_col_spacings (GTK_TABLE (table), 40);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(CCWin)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                /* This simply creates a grid of Lables with text on the table */
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter Number of Phasors</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 1, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                /* Create text boxes for user to enter appropriate values */
                phtext = gtk_entry_new ();
                gtk_table_attach_defaults (GTK_TABLE (table), phtext, 1, 2, 3, 4);
                gtk_widget_show (phtext);
                memset(line, '\0', 50);
                memset(buff, '\0', 10);
                strcat(line, "Note : Maximum Removal upto ");
                sprintf(buff,"%d",cfg_info->cfg_phnmr_val);
                strcat(line, buff);
                strcat(line, "       ");
                label = gtk_label_new (line);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 1, 2, 4, 5);
                gtk_widget_show (label);
                /* Add a "next" button to the bottom of the dialog */
                next_butn = gtk_button_new_with_label ("Next");
                /* Signal handling for buttons on Window */
                g_signal_connect (next_butn, "clicked", G_CALLBACK (validation_remove_ph_an_num), (gpointer) "1");
                g_signal_connect_swapped (CCWin, "response", G_CALLBACK (gtk_widget_destroy), CCWin);
                /* This makes it so the button is the default */
                gtk_widget_set_can_default (next_butn, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (CCWin)->action_area), next_butn, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (next_butn);
                gtk_widget_show (next_butn);
                /* Finally show the CCWin */
                gtk_widget_show (CCWin);
        };
int validation_analog_names (GtkWidget * widget, gpointer udata)
Definition at line 266 of file CfgGuiFunctions.c.
References AnalogChWin, ConfigurationFrame::cfg_analog_channels, ConfigurationFrame::cfg_annmr_val, cfg_info, channel_names_for_digital(), i, j, num_text, and validation_result().
Referenced by channel_names_for_analog().
        {
                /* local variables */
                int ia, i, j, ia1 = 0, vtr;
                char stn[16], c = ' ';
                char *display_msg;
                const char *aa[20];
                /* First get how many Analog channel we have? */
                vtr = cfg_info->cfg_annmr_val+1;
                memset(stn, '\0', 16);
                /* Allocate the memory for Analog channel names */
                cfg_info->cfg_analog_channels = (char *)malloc((vtr*16) * sizeof(char));
                memset(cfg_info->cfg_analog_channels, '\0', sizeof(cfg_info->cfg_analog_channels));
                for (ia=1; ia<vtr; ia++)
                {
                        /* Get the text entry value filled by user */
                        aa[ia] = gtk_entry_get_text(GTK_ENTRY(num_text[ia]));
                        if(strlen(aa[ia]) == 0)
{
                                free (cfg_info->cfg_analog_channels);
                                display_msg = "\t\tPlease enter Analog channel name\t\t\n";
                                validation_result (display_msg);        /* Show the unsuccess message to user */
                                return 1;
                        }
                        else
{
                                memset(stn, '\0', 16);
                                strcpy(stn, aa[ia]);
                                j = strlen(stn);
                                if(j < 17)
{
                                        for(i = j; i < 16 ; i++)
{
                                                stn[i] =  c;
                                        }
                                }
                        }
                        for (i=0; i< 16 && i< vtr*16; i++, ia1++)
{
                                /* Copy all phasor name in an array */
                                cfg_info->cfg_analog_channels[ia1] = stn[i];
                        }
                }
                /* Close/destroy the AnalogChWin */
                gtk_widget_destroy(AnalogChWin);
                /* Next call for Enter Digital channels */
                channel_names_for_digital ();
                return 0;
        };
int validation_cfg_create ()
Definition at line 85 of file CfgGuiFunctions.c.
References ConfigurationFrame::cfg_af, ConfigurationFrame::cfg_annmr_val, ConfigurationFrame::cfg_dataRate, ConfigurationFrame::cfg_dgnmr_val, ConfigurationFrame::cfg_fdf, cfg_info, _pmuStruct::cfg_modification_button, ConfigurationFrame::cfg_pf, ConfigurationFrame::cfg_phnmr_val, ConfigurationFrame::cfg_pmuID, ConfigurationFrame::cfg_pn, cfg_setup_window, ConfigurationFrame::cfg_STNname, channel_names_for_phasor(), _pmuStruct::header_frm_button, i, isNumber(), j, p_af, p_anNumber, p_dgNumber, p_drate, p_ff, p_id, p_pf, p_phNumber, p_pn, p_stn, pmu_data, _pmuStruct::pmu_details_button, and validation_result().
Referenced by cfg_create_function().
        {
                /* local variables */
                int i, j;
                const char *text, *text1, *text2, *text3, *text4;
                const char *text5, *text6, *text7, *text8, *text9;
                char *display_msg, stn[16], c = ' ';
                /* Get the text entries  and combo box values filled by user */
                text  = gtk_entry_get_text(GTK_ENTRY(p_id));
                text1 = gtk_entry_get_text(GTK_ENTRY(p_stn));
                text2 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_ff));
                text3 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_af));
                text4 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_pf));
                text5 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_pn));
                text6 = gtk_entry_get_text(GTK_ENTRY(p_phNumber));
                text7 = gtk_entry_get_text(GTK_ENTRY(p_anNumber));
                text8 = gtk_entry_get_text(GTK_ENTRY(p_dgNumber));
                text9 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_drate));
                if(!isNumber((char *)text))     /* Check text_box entry for valid integer or not?  */
                {
                        display_msg = "\tPlease enter valid value for PMU ID code\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 0;
                }
                else if(strlen(text1) == 0)     /* Check text_box entry should not be NULL */
                {
                        display_msg = "\tPlease enter  PMU Station name\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 0;
                }
                else if(!isNumber((char *)text6) && atoi(text6) > 0)    /* Check text_box entry for valid integer or not? as well as greater than one */
                {
                        display_msg = "\tPlease enter valid value for Phasor Number\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 0;
                }
                else if(!isNumber((char *)text7))               /* Check text_box entry for valid integer or not?  */
                {
                        display_msg = "\tPlease enter valid value for Analog Number\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 0;
                }
                else if(!isNumber((char *)text8))               /* Check text_box entry for valid integer or not?  */
                {
                        display_msg = "\tPlease enter valid value for Digital Number\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 0;
                }
                else            /* Only if all the text_box entries were right */
                {
                        /* Allocate the memory for the ConfigurationFrame object */
                        cfg_info = malloc(sizeof(struct ConfigurationFrame));
                        cfg_info->cfg_STNname = malloc(16);
                        memset(cfg_info->cfg_STNname,'\0',16);
                        memset(stn, '\0', 16);
                        strcpy(stn, text1);
                        j = strlen(stn);
                        for(i = j; i < 16 ; i++)
{
                                stn[i] =  c;
                        }
                        cfg_info->cfg_pmuID = atoi(text);
                        strcpy(cfg_info->cfg_STNname, stn);
                        cfg_info->cfg_phnmr_val = atoi(text6);
                        cfg_info->cfg_annmr_val = atoi(text7);
                        cfg_info->cfg_dgnmr_val = atoi(text8);
                        cfg_info->cfg_dataRate = atoi(text9);
                        if(!strcmp(text2, "Fix Point"))
                                cfg_info->cfg_fdf = 0;
                        else
                                cfg_info->cfg_fdf = 1;
                        if(!strcmp(text3, "Fix Point"))
                                cfg_info->cfg_af = 0;
                        else
                                cfg_info->cfg_af = 1;
                        if(!strcmp(text4, "Fix Point"))
                                cfg_info->cfg_pf = 0;
                        else
                                cfg_info->cfg_pf = 1;
                        if(!strcmp(text5, "Ractangular"))
                                cfg_info->cfg_pn = 0;
                        else
                                cfg_info->cfg_pn = 1;
                        /* Close/destroy the cfg_setup_window */
                        gtk_widget_destroy(cfg_setup_window);
                        /* Enable all (mentioned) buttons on main PMU Simulator main window */
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->header_frm_button), TRUE);
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->pmu_details_button), TRUE);
                        gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->cfg_modification_button), TRUE);
                        /* Next call for Enter Phasor channels */
                        channel_names_for_phasor ();
                        return 1;
                }
        };
int validation_digital_names (GtkWidget * widget, gpointer udata)
Definition at line 332 of file CfgGuiFunctions.c.
References AnalogChWin, ConfigurationFrame::cfg_dgnmr_val, ConfigurationFrame::cfg_digital_channels, cfg_info, final_cfg_create(), i, j, num_text, and validation_result().
Referenced by channel_names_for_digital().
        {
                /* local variables */
                int ia, i, j, ia1 = 0, vtr;
                char stn[16], c = ' ';
                char *display_msg;
                const char *aa[20];
                /* First get how many Digital channel we have? */
                vtr = cfg_info->cfg_dgnmr_val*16+1;
                memset(stn, '\0', 16);
                /* Allocate the memory for Digital channel names */
                cfg_info->cfg_digital_channels = (char *)malloc((vtr*16) * sizeof(char));
                memset(cfg_info->cfg_digital_channels, '\0', sizeof(cfg_info->cfg_digital_channels));
                for (ia=1; ia<vtr; ia++)
                {
                        /* Get the text entry value filled by user */
                        aa[ia] = gtk_entry_get_text(GTK_ENTRY(num_text[ia]));
                        if(strlen(aa[ia]) == 0)
{
                                free (cfg_info->cfg_digital_channels);
                                display_msg = "\t\tPlease enter Digital channel names\t\t\n";
                                validation_result (display_msg);        /* Show the unsuccess message to user */
                                return 1;
                        }
                        else
{
                                memset(stn, '\0', 16);
                                strcpy(stn, aa[ia]);
                                j = strlen(stn);
                                if(j < 17)
{
                                        for(i = j; i < 16 ; i++)
{
                                                stn[i] =  c;
                                        }
                                }
                        }
                        for (i=0; i< 16 && i< vtr*16; i++, ia1++)
{
                                /* Copy all digital name in an array */
                                cfg_info->cfg_digital_channels[ia1] = stn[i];
                        }
                }
                /* Close/destroy the AnalogChWin */
                gtk_widget_destroy(AnalogChWin);
                /* Next call for finaly create Configuration Frame */
                final_cfg_create ();
                return 0;
        };
void validation_hdr_frm (GtkWidget * widget, gpointer udata)
Definition at line 676 of file CfgGuiFunctions.c.
References CCWin, hdr_frame, HdrFrm, header_frm_gen(), i, j, and validation_result().
Referenced by hdr_create_function().
        {
                /* local variables */
                int i, j;
                const char *text;
                /* Get the text entry value filled by user */
                text = gtk_entry_get_text(GTK_ENTRY(HdrFrm));
                i = strlen(text);
                if(i > 0)
                {
                        hdr_frame = (char *)malloc(i * sizeof(char));
                        memset(hdr_frame, '\0', sizeof(hdr_frame));
                        for (j=0; j<i ; j++)
{
                                hdr_frame[j] = text[j];
                        }
                        /* Close/destroy the CCWin */
                        gtk_widget_destroy(CCWin);
                        /* Finally call below function to generate header frame */
                        header_frm_gen(i);
                }
                else
                {
                        validation_result ("Pleas enter the Header Frame details...!!!");       /* Show the unsuccess message to user */
                }
        };
int validation_new_analog_names (GtkWidget * widget, gpointer udata)
Definition at line 515 of file CfgGuiFunctions.c.
References change_data_rate_option(), i, j, ConfigurationChange::new_cfg_analog_channels, ConfigurationChange::new_cfg_annmr_val, new_cfg_info, num_text, PhasorChWin, and validation_result().
Referenced by new_channel_names_for_analog().
        {
                /* local variables */
                int ia, i, j, ia1 = 0, vtr;
                char stn[16], c = ' ';
                char *display_msg;
                const char *aa[20];
                /* First get how many New Analog channel he wants to add? */
                vtr = new_cfg_info->new_cfg_annmr_val+1;
                memset(stn, '\0', 16);
                /* Allocate the memory for New Analog channel names */
                new_cfg_info->new_cfg_analog_channels = (char *)malloc((vtr*16) * sizeof(char));
                memset(new_cfg_info->new_cfg_analog_channels, '\0', sizeof(new_cfg_info->new_cfg_analog_channels));
                for (ia=1; ia<vtr; ia++)
                {
                        /* Get the text entry value filled by user */
                        aa[ia] = gtk_entry_get_text(GTK_ENTRY(num_text[ia]));
                        if(strlen(aa[ia]) == 0)
{
                                free (new_cfg_info->new_cfg_analog_channels);
                                display_msg = "\t\tPlease enter Analog channel name\t\t\n";
                                validation_result (display_msg);        /* Show the unsuccess message to user */
                                return 1;
                        }
                        else
{
                                memset(stn, '\0', 16);
                                strcpy(stn, aa[ia]);
                                j = strlen(stn);
                                if(j < 17)
{
                                        for(i = j; i < 16 ; i++)
{
                                                stn[i] =  c;
                                        }
                                }
                        }
                        for (i=0; i< 16 && i< vtr*16; i++, ia1++)
{
                                /* Copy all Analog name in an array */
                                new_cfg_info->new_cfg_analog_channels[ia1] = stn[i];
                        }
                }
                /* Close/destroy the PhasorChWin */
                gtk_widget_destroy(PhasorChWin);
                /* Next call for Data Rate change option? */
                change_data_rate_option();
                return 0;
        };
int validation_new_data_rate (GtkButton * but, gpointer udata)
Definition at line 581 of file CfgGuiFunctions.c.
References CCWin, ConfigurationChange::data_rate_choice, isNumber(), new_cfg_info, ConfigurationChange::new_data_rate, p_drate, reconfig_cfg_CC(), and validation_result().
Referenced by enter_new_data_rate().
        {
                /* local variables */
                char *display_msg;
                const char *text;
                /* Get the combo box value selected by user */
                text  = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_drate));
                if(isNumber((char *)text))      /* Check text_box entry for valid integer or not?  */
                {
                        new_cfg_info->data_rate_choice = 1;
                        new_cfg_info->new_data_rate = atoi(text);
                        /* Close/destroy the CCWin */
                        gtk_widget_destroy(CCWin);
                        /* Final call to recreate configuration frame */
                        reconfig_cfg_CC();
                        return 0;
                }
                else
                {
                        display_msg = "\tPlease enter valid value for data rate.\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 1;
                }
        };
int validation_new_phasor_names (GtkWidget * widget, gpointer udata)
Definition at line 449 of file CfgGuiFunctions.c.
References i, j, new_analog_num(), new_cfg_info, ConfigurationChange::new_cfg_phasor_channels, ConfigurationChange::new_cfg_phnmr_val, num_text, PhasorChWin, and validation_result().
Referenced by new_channel_names_for_phasor().
        {
                /* local variables */
                int ia, i, j, ia1 = 0, vtr;
                char stn[16], c = ' ';
                char *display_msg;
                const char *aa[20];
                /* First get how many New Phasor channel he wants to add? */
                vtr = new_cfg_info->new_cfg_phnmr_val+1;
                memset(stn, '\0', 16);
                /* Allocate the memory for New Phasor channel names */
                new_cfg_info->new_cfg_phasor_channels = (char *)malloc((vtr*16) * sizeof(char));
                memset(new_cfg_info->new_cfg_phasor_channels, '\0', sizeof(new_cfg_info->new_cfg_phasor_channels));
                for (ia=1; ia<vtr; ia++)
                {
                        /* Get the text entry value filled by user */
                        aa[ia] = gtk_entry_get_text(GTK_ENTRY(num_text[ia]));
                        if(strlen(aa[ia]) == 0)
{
                                free (new_cfg_info->new_cfg_phasor_channels);
                                display_msg = "\t\tPlease enter Phasor channel name\t\t\n";
                                validation_result (display_msg);                /* Show the unsuccess message to user */
                                return 1;
                        }
                        else
{
                                memset(stn, '\0', 16);
                                strcpy(stn, aa[ia]);
                                j = strlen(stn);
                                if(j < 17)
{
                                        for(i = j; i < 16 ; i++)
{
                                                stn[i] =  c;
                                        }
                                }
                        }
                        for (i=0; ((i< 16) && (i< vtr*16)); i++, ia1++)
{
                                /* Copy all phasor name in an array */
                                new_cfg_info->new_cfg_phasor_channels[ia1] = stn[i];
                        }
                }
                /* Close/destroy the PhasorChWin */
                gtk_widget_destroy(PhasorChWin);
                /* Next call for Enter New Phasor channels */
                new_analog_num();
                return 0;
        };
int validation_ph_an_num (GtkButton * but, gpointer udata)
Definition at line 399 of file CfgGuiFunctions.c.
References isNumber(), ConfigurationChange::new_cfg_annmr_val, new_cfg_info, ConfigurationChange::new_cfg_phnmr_val, new_channel_names_for_analog(), new_channel_names_for_phasor(), phtext, and validation_result().
Referenced by new_analog_num(), and new_phasor_num().
        {
                /* local variables */
                const char *text;
                char *display_msg, find_butn[2];
                /* Get the text entry value filled by user */
                text  = gtk_entry_get_text(GTK_ENTRY(phtext));
                /* Use udata for idenifing signal button */
                strcpy(find_butn,(char *) udata);
                if(isNumber((char *)text))      /* Check text_box entry for valid integer or not?  */
                {
                        if(!strcmp(find_butn, "1"))     /* If user wants to add new phasor channels */
{
                                new_cfg_info->new_cfg_phnmr_val = atoi(text);
                                /* Next call for Enter New Phasor channels */
                                new_channel_names_for_phasor ();
                                return 0;
                        }
                        else if(!strcmp(find_butn, "2"))        /* If user wants to add new Analog channels */
{
                                new_cfg_info->new_cfg_annmr_val = atoi(text);
                                /* Next call for Enter New Phasor channels */
                                new_channel_names_for_analog ();
                                return 0;
                        }
                }
                else
                {
                        display_msg = "\nPlease enter the valid value in the given field\n";
                        validation_result (display_msg);                /* Show the unsuccess message to user */
                        return 1;
                }
                return 1;
        };
int validation_phasor_names (GtkWidget * widget, gpointer udata)
Definition at line 200 of file CfgGuiFunctions.c.
References cfg_info, ConfigurationFrame::cfg_phasor_channels, ConfigurationFrame::cfg_phnmr_val, channel_names_for_analog(), i, j, num_text, PhasorChWin, and validation_result().
Referenced by channel_names_for_phasor().
        {
                /* local variables */
                int ia, i, j, ia1 = 0, vtr;
                char stn[16], c = ' ';
                char *display_msg;
                const char *aa[20];
                /* First get how many Phasor channel we have? */
                vtr = cfg_info->cfg_phnmr_val+1;
                memset(stn, '\0', 16);
                /* Allocate the memory for Phasor channel names */
                cfg_info->cfg_phasor_channels = (char *)malloc((vtr*16) * sizeof(char));
                memset(cfg_info->cfg_phasor_channels, '\0', sizeof(cfg_info->cfg_phasor_channels));
                for (ia=1; ia<vtr; ia++)
                {
                        /* Get the text entry value filled by user */
                        aa[ia] = gtk_entry_get_text(GTK_ENTRY(num_text[ia]));
                        if(strlen(aa[ia]) == 0)
{
                                free (cfg_info->cfg_phasor_channels);
                                display_msg = "\t\tPlease enter Phasor channel name\t\t\n";
                                validation_result (display_msg);                /* Show the unsuccess message to user */
                                return 1;
                        }
                        else
{
                                memset(stn, '\0', 16);
                                strcpy(stn, aa[ia]);
                                j = strlen(stn);
                                if(j < 17)
{
                                        for(i = j; i < 16 ; i++)
{
                                                stn[i] =  c;
                                        }
                                }
                        }
                        for (i=0; i< 16 && i< vtr*16; i++, ia1++)
{
                                /* Copy all phasor name in an array */
                                cfg_info->cfg_phasor_channels[ia1] = stn[i];
                        }
                }
                /* Close/destroy the PhasorChWin */
                gtk_widget_destroy(PhasorChWin);
                /* Next call for Enter Analog channels */
                channel_names_for_analog ();
                return 0;
        };
int validation_remove_ph_an_num (GtkButton * but, gpointer udata)
Definition at line 619 of file CfgGuiFunctions.c.
References CCWin, ConfigurationFrame::cfg_annmr_val, cfg_info, ConfigurationFrame::cfg_phnmr_val, change_data_rate_option(), isNumber(), ConfigurationChange::new_cfg_annmr_val, new_cfg_info, ConfigurationChange::new_cfg_phnmr_val, phtext, remove_analog_num(), and validation_result().
Referenced by remove_analog_num(), and remove_phasor_num().
        {
                /* local variables */
                const char *text;
                char *display_msg, find_butn[2];
                /* Get the text entry value filled by user */
                text  = gtk_entry_get_text(GTK_ENTRY(phtext));
                strcpy(find_butn,(char *) udata);
                if(isNumber((char *)text))      /* Check text_box entry for valid integer or not?  */
                {
                        if(!strcmp(find_butn, "1") && atoi(text) < cfg_info->cfg_phnmr_val )    /* Atleast one phasor should be present there in CFG Frame */
{
                                /* If Phasor removal? */
                                new_cfg_info->new_cfg_phnmr_val = atoi(text);
                                /* Next call to remove */
                                remove_analog_num ();
                                return 0;
                        }
                        else if(!strcmp(find_butn, "2") && atoi(text) <= cfg_info->cfg_annmr_val )
{
                                /* If Analog removal? */
                                new_cfg_info->new_cfg_annmr_val = atoi(text);
                                /* Close/destroy the CCWin */
                                gtk_widget_destroy(CCWin);
                                change_data_rate_option();
                                return 0;
                        }
                        else
{
                                display_msg = "\t\tPlease enter value within max range!\t\t\n";
                                validation_result (display_msg);        /* Show the unsuccess message to user */
                                return 1;
                        }
                }
                else
                {
                        display_msg = "\t\tPlease enter valid value in the field\t\t\n";
                        validation_result (display_msg);        /* Show the unsuccess message to user */
                        return 1;
                }
        };