PMUSimulator: PmuGui.c File Reference
PmuGui.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <ctype.h>
#include <gtk/gtk.h>
#include "PmuGui.h"
#include "ServerFunction.h"
Functions
int isNumber (char *s)
int checkip (char ip[])
void destroy (GtkWidget *widget, gpointer udata)
void destroy1 (GtkWidget *widget, gpointer udata)
void about_pmu (GtkButton *widget, gpointer udata)
void Pmu_Help (GtkButton *but, gpointer udata)
void validation_result (char *msg)
void pmu_colors ()
int validation_pmu_server (GtkButton *button, gpointer udata)
void pmu_server ()
Function Documentation
void about_pmu (GtkButton * widget, gpointer udata)
Definition at line 159 of file PmuGui.c.
Referenced by main().
        {
                /* local variables */
                GtkWidget *about_dialog;
                const gchar    *auth[] = {"\nDr. A.M. Kulkarni <http://www.ee.iitb.ac.in/wiki/faculty/anil>", "\nProf. S.U. Ghumbre <shashi.comp@coep.ac.in>", "\nProf. V.Z. Attar <vahida.comp@coep.ac.in>", "\nNitesh Pandit <panditnitesh@gmail.com>", "\nKedar V. Khandeparkar <kedar.khandeparkar@gmail.com>", NULL};
                /* Create a about dialog for displaying about the iPDC. */
                about_dialog = gtk_about_dialog_new ();
                /* Define the diffrent properties of about_dialog. */
                gtk_about_dialog_set_program_name ((GtkAboutDialog *)about_dialog, "\t\tPMU Simulator 1.0\t\t");
                gtk_about_dialog_set_comments ((GtkAboutDialog *)about_dialog, "A Phasor Measurement Unit Simulator for WAMS.\n\nUnder guidance of Dr. A.M. Kulkarni\nDepartment of Electrical Engineering\nIndian Institute of Technology, Bombay\nMumbai, INDIA\n\nAuthors: Nitesh Pandit\n\t\t\t  Kedar Khandeparkar");
                gtk_about_dialog_set_license ((GtkAboutDialog *)about_dialog, "\t\tPMU Simulator - A Phasor Measurement Unit Simulator\n\nGeneral Public License (GPL)\n\nAuthors:\n\t\tNitesh Pandit <panditnitesh@gmail.com>\n\t\tKedar V. Khandeparkar <kedar.khandeparkar@gmail.com>\n\n\nThis program is free software; you can redistribute it and/or\nmodify it under the terms of the GNU General Public License\nas published by the Free Software Foundation; either version 2\nof the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.\n");
                gtk_about_dialog_set_copyright ((GtkAboutDialog *)about_dialog, "Copyright (C) 2010-2011 GPL-3.0");
                gtk_about_dialog_set_website ((GtkAboutDialog *)about_dialog, "http://wafms.co.cc/ipdc/");
                gtk_about_dialog_set_authors ((GtkAboutDialog *)about_dialog, auth);
                /* Ensure that the dialog box is destroyed when the user responds */
                g_signal_connect_swapped (about_dialog, "response", G_CALLBACK (gtk_widget_destroy), about_dialog);
                /* Finally show the about_dialog. */
                gtk_widget_show_all (about_dialog);
        };
int checkip (char ip[])
Definition at line 98 of file PmuGui.c.
        {
                struct sockaddr_in sa;
                int result = inet_pton(AF_INET, ip, &(sa.sin_addr));
                return result;
        };
void destroy (GtkWidget * widget, gpointer udata)
Definition at line 112 of file PmuGui.c.
References pid.
Referenced by main().
        {
                g_print ("\nPMU Simulator Closing....!!!\n");
                if(!kill(pid, SIGKILL))
                {
                        printf("Sent a SIGKILL signal to Process ID %d\n",pid);
                }
                else
                {
                        printf("Signal not sent to %d\n",pid);
                }
                gtk_main_quit();
                exit(1);
        };
void destroy1 (GtkWidget * widget, gpointer udata)
Definition at line 134 of file PmuGui.c.
References pid, and srvr_entry.
Referenced by pmu_server().
        {
                if (srvr_entry == 0)
                {
                        g_print ("\nPMU Simulator Closing....!!!\n");
                        if(!kill(pid, SIGKILL))
{
                                printf("Sent a SIGKILL signal to Process ID %d\n",pid);
                        }
                        else
{
                                printf("Signal not sent to %d\n",pid);
                        }
                        gtk_main_quit();
                        exit(1);
                }
        };
int isNumber (char * s)
Definition at line 67 of file PmuGui.c.
Referenced by validation_cfg_create(), validation_new_data_rate(), validation_ph_an_num(), validation_pmu_server(), and validation_remove_ph_an_num().
        {
            int dot=0, num=0, end=0;
            while(isspace(*s))s++;
            if(*s == '-')s++;
            if(! *s)return 0;
            while(*s)
                if(isspace(*s))
                    end=1, s++;
                else if(end)
                    return 0;
                else if(isdigit(*s))
                    num=1, s++;
                else if(*s=='.')
                    if(dot)
                        return 0;
                    else
                        dot=1,s++;
                else
                    return 0;
            return num;
        };
void pmu_colors ()
Definition at line 239 of file PmuGui.c.
References _pmuStruct::admin_label, _pmuStruct::footer_label, _pmuStruct::img_label, _pmuStruct::logo_butun, markup, pmu_data, and _pmuStruct::welcome_pmu.
Referenced by main().
        {
                /* Set the font and color for the heading on 'welcome_pmu' lable */
                markup = g_markup_printf_escaped ("<span foreground=\"#2F4F4F\" font='18'><b>\tPhasor Measurement Unit\n\t\t  PMU Simulator</b></span>");
                gtk_label_set_markup (GTK_LABEL (pmu_data->welcome_pmu), markup);
                g_free (markup);
                markup = g_markup_printf_escaped ("<span foreground=\"#330000\" font='8'><b>\n-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n</b>\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tAll Rights Reserved\n</span>");//\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b>Indian Institute of Technology, Bombay</b></span>");
                gtk_label_set_markup (GTK_LABEL (pmu_data->footer_label), markup);
                g_free (markup);
                markup = g_markup_printf_escaped ("<span foreground=\"#333333\" font='10'><b>Admin Operations</b></span>");
                gtk_label_set_markup (GTK_LABEL (pmu_data->admin_label), markup);
                g_free (markup);
                /* Add a "close" button to the bottom of the dialog */
                GdkColor color;
                GtkWidget *image, *image1;
                gdk_color_parse( "#999999", &color );
                gtk_widget_modify_bg( GTK_WIDGET(pmu_data->img_label), GTK_STATE_NORMAL, &color );
                /* Set the general image on a button */
                image = gtk_image_new_from_file("PSLab.PNG");
                gtk_button_set_image ((GtkButton *)pmu_data->img_label, image);
                gtk_widget_show (pmu_data->img_label);
                /* Set the image (PMU-logo) on a specific button */
                image1 = gtk_image_new_from_file("PmuLogo.png");
                gtk_button_set_image ((GtkButton *)pmu_data->logo_butun, image1);
                gtk_widget_show (pmu_data->logo_butun);
        };
void Pmu_Help (GtkButton * but, gpointer udata)
Definition at line 192 of file PmuGui.c.
Referenced by cfg_create_function(), and pmu_server().
        {
                GtkWidget *help_dialog;
                /* Create the widgets */
                help_dialog = gtk_about_dialog_new ();
                //GtkWidget *image1 = gtk_image_new_from_file("pdcIMG.jpg");
                gtk_about_dialog_set_program_name ((GtkAboutDialog *)help_dialog, "PMU HELP\n\n");
                gtk_about_dialog_set_comments ((GtkAboutDialog *)help_dialog, "1) ID Code ex. 50, 60, etc.\t\t\t\t\t\t\n\n   2) Port should be greater than 1500 and less than 65535.\n\n3) Channel Name should be less than 16 characters.\t\n\n4) Fixed/Floating point and Rectangular/Polar are the\nrepresentation of measured values.\n\n");
                /* Ensure that the dialog box is destroyed when the user responds */
                g_signal_connect_swapped (help_dialog, "response", G_CALLBACK (gtk_widget_destroy), help_dialog);
                gtk_widget_show_all (help_dialog);
        };
void pmu_server ()
Definition at line 332 of file PmuGui.c.
References destroy1(), markup, p_port, p_protocol, Pmu_Help(), pmu_server_window, validation_pmu_server(), and validation_result().
Referenced by main().
        {
                /* local variables */
                GtkWidget *table, *label;
                GtkWidget *valdbutton, *help_button;
                /* Create a new dialog window for PMU Server Setup */
                pmu_server_window = gtk_dialog_new ();
                g_signal_connect (pmu_server_window, "destroy", G_CALLBACK (gtk_widget_destroy), pmu_server_window);
                gtk_window_set_title (GTK_WINDOW (pmu_server_window), "PMU Server Setup");
                gtk_container_set_border_width (GTK_CONTAINER (pmu_server_window), 10);
                gtk_widget_set_size_request (pmu_server_window, 350, 300);
                /* Create a table of 4 by 2 squares. */
                table = gtk_table_new (4, 2, FALSE);
                /* Set the spacing to 50 on x and 5 on y */
                gtk_table_set_row_spacings (GTK_TABLE (table), 50);
                gtk_table_set_col_spacings (GTK_TABLE (table), 5);
                /* Pack the table into the window */
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG(pmu_server_window)->vbox), table, TRUE, TRUE, 0);
                gtk_widget_show (table);
                /* Add few buttons to the bottom of the dialog */
                valdbutton = gtk_button_new_with_label ("Run");
                help_button = gtk_button_new_with_label ("Help");
                /* This simply creates a grid of toggle buttons on the table */
                label = gtk_label_new (" ");
                markup = g_markup_printf_escaped ("<span foreground=\"#990033\" font='12'><b>Enter PMU Server Details</b></span>");
                gtk_label_set_markup (GTK_LABEL (label), markup);
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 2, 0, 1);
                gtk_widget_show (label);
                g_free (markup);
                label = gtk_label_new ("Server Port");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 2, 3);
                gtk_widget_show (label);
                label = gtk_label_new ("Protocol   ");
                gtk_table_attach_defaults (GTK_TABLE (table), label, 0, 1, 3, 4);
                gtk_widget_show (label);
                /* Create text boxes for user to enter appropriate values */
                p_port = gtk_entry_new();
                gtk_entry_set_max_length ((GtkEntry *)p_port, 5);
                gtk_table_attach_defaults (GTK_TABLE (table), p_port, 1, 2, 2, 3);
                gtk_widget_show (p_port);
                /* Create combo boxe for user with some fixed values */
                p_protocol = gtk_combo_box_new_text();
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_protocol), "UDP");
                gtk_combo_box_append_text(GTK_COMBO_BOX(p_protocol), "TCP");
                gtk_combo_box_set_active(GTK_COMBO_BOX(p_protocol), 0);
                gtk_table_attach_defaults (GTK_TABLE (table), p_protocol, 1, 2, 3, 4);
                gtk_widget_show (p_protocol);
                /* Signal handling for buttons on PMU Server Setup Window */
                g_signal_connect_swapped (valdbutton, "clicked", G_CALLBACK (validation_pmu_server), valdbutton);
                g_signal_connect_swapped (help_button, "clicked", G_CALLBACK (Pmu_Help), NULL);
                g_signal_connect (pmu_server_window, "destroy", G_CALLBACK(destroy1), NULL);
                /* This makes it so the button is the default. */
                gtk_widget_set_can_default (valdbutton, TRUE);
                gtk_widget_set_can_default (help_button, TRUE);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (pmu_server_window)->action_area), valdbutton, TRUE, TRUE, 0);
                gtk_box_pack_start (GTK_BOX (GTK_DIALOG (pmu_server_window)->action_area), help_button, TRUE, TRUE, 0);
                /* This grabs this button to be the default button. Simply hitting the "Enter" key will cause this button to activate. */
                gtk_widget_grab_default (valdbutton);
                gtk_widget_show (valdbutton);
                gtk_widget_grab_default (help_button);
                gtk_widget_show (help_button);
                /* Finally show the pmu_server_window */
                gtk_widget_show (pmu_server_window);
                validation_result ("\t\tPlease first enter the details for PMU setup.\t\t\n");          /* Show the popup window to user */
        };
int validation_pmu_server (GtkButton * button, gpointer udata)
Definition at line 279 of file PmuGui.c.
References isNumber(), p_port, p_protocol, pmu_server_window, srvr_entry, and validation_result().
Referenced by pmu_server().
        {
                /* local variables */
                char *errmsg1, tmp[4];
                const char *text1, *text2;
                FILE *fp;
                srvr_entry = 0;
                /* Get the text entries filled by user */
                text1 = gtk_entry_get_text(GTK_ENTRY(p_port));
                text2 = gtk_combo_box_get_active_text(GTK_COMBO_BOX(p_protocol));
                memset(tmp,'\0',4);
                strcpy (tmp, text2);
                if(!isNumber((char *)text1) && (atoi(text1) < 1500 || (atoi(text1) > 65535)))   /* Check for valid port number */
                {
                        errmsg1 = "\tPlease enter valid value for PMU Server Port\t\n";
                        validation_result (errmsg1);            /* Show the unsuccess message to user */
                        return 0;
                }
                else
                {
                        srvr_entry = 1;
                        /* Open the file "PmuServer.txt" in write mode */
                        if((fp=fopen("PmuServer.txt", "wb"))==NULL)
{
                                printf("Cannot open file.\n");
                                exit(1);
                        }
                        /* Write the information entered by user */
                        fputs(text1, fp);
                        fputc(' ', fp);
                        fputs(text2, fp);
                        fclose(fp);
                        /* Close/destroy the pmu_server_window */
                        gtk_widget_destroy(pmu_server_window);
                        errmsg1 = "\t\tPMU Server run Successfully\t\t\n";
                        validation_result (errmsg1);            /* Show the success message to user */
                        return 1;
                }
        };
void validation_result (char * msg)
Definition at line 214 of file PmuGui.c.
Referenced by cfg_STAT_change(), create_cfg(), final_cfg_create(), header_frm_gen(), pmu_server(), reconfig_cfg_CC(), validation_analog_names(), validation_cfg_create(), validation_digital_names(), validation_hdr_frm(), validation_new_analog_names(), validation_new_data_rate(), validation_new_phasor_names(), validation_ph_an_num(), validation_phasor_names(), validation_pmu_server(), and validation_remove_ph_an_num().
        {
                GtkWidget *val_dialog;
                /* Create the widgets a new dialog box */
                val_dialog = gtk_about_dialog_new ();
                /* Define the diffrent properties of val_dialog. */
                gtk_about_dialog_set_program_name ((GtkAboutDialog *)val_dialog, " ");
                gtk_about_dialog_set_comments ((GtkAboutDialog *)val_dialog, msg);
                /* Ensure that the dialog box is destroyed when the user responds */
                g_signal_connect_swapped (val_dialog, "response", G_CALLBACK (gtk_widget_destroy), val_dialog);
                /* Finally show the val_dialog. */
                gtk_widget_show_all (val_dialog);
        };