PMUSimulator: pmu.c File Reference
pmu.c File Reference
#include <stdio.h>
#include <signal.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <pthread.h>
#include <gtk/gtk.h>
#include "PmuGui.h"
#include "ServerFunction.h"
#include "CfgGuiFunctions.h"
#include "CfgFunction.h"
Defines
#define UI_fILE "pmu.glade"
#define GW(name) CH_GET_WIDGET(builder, name, pmu_data)
Functions
int main (int argc, char **argv)
Define Documentation
#define GW (name) CH_GET_WIDGET(builder, name, pmu_data)
Referenced by main().
#define UI_fILE "pmu.glade"
Definition at line 47 of file pmu.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 53 of file pmu.c.
References _pmuStruct::about_menuitem, about_pmu(), cfg_chng_options(), cfg_create_function(), _pmuStruct::cfg_modification_button, create_cfg(), _pmuStruct::create_cfg_button, destroy(), _pmuStruct::E_button, _pmuStruct::exit_button, _pmuStruct::exit_menuitem, GW, hdr_create_function(), _pmuStruct::header_frm_button, pid, pmu_colors(), pmu_data, _pmuStruct::pmu_details_button, pmu_server(), _pmuStruct::Pmu_Simulator, show_pmu_details(), start_server(), and UI_fILE.
        {
                /* local variables */
                GtkBuilder *builder;
                GError     *error = NULL;
                pid = fork();
                if (pid == 0)
                {
                        /* Child process for PMU SERVER Setup */
                        start_server();
                }
                else
                {
                        /* Main process for PMU Configuration Setup */
                        /* Init GTK+ */
                        gtk_init(&argc, &argv);
                        /* Create new GtkBuilder object */
                        builder = gtk_builder_new();
                        /* Add glade file to GtkBuilder */
                        if(!gtk_builder_add_from_file(builder, UI_fILE, &error))
{
                                g_warning("%s", error->message);
                                g_free(error);
                                return(1);
                        }
                        /* Allocate data structure */
                        pmu_data = g_slice_new(pmuStruct);
                        /* Get objects from UI */
                        #define GW(name) CH_GET_WIDGET(builder, name, pmu_data)
                        GW(Pmu_Simulator);
                        GW(create_cfg_button);
                        GW(header_frm_button);
                        GW(pmu_details_button);
                        GW(cfg_modification_button);
                        GW(pmu_menubar);
                        GW(img_label);
                        GW(welcome_pmu);
                        GW(admin_label);
                        GW(logo_butun);
                        GW(exit_button);
                        GW(footer_label);
                        GW(about_menuitem);
                        GW(exit_menuitem);
                        GW(E_button);
                        #undef GW
                        /* Connect signal to builder */
                        gtk_builder_connect_signals(builder, pmu_data);
                        gtk_builder_connect_signals(builder, NULL);
                        /* Set the Title of Main Window */
                        gtk_window_set_title (GTK_WINDOW (pmu_data->Pmu_Simulator), "PMU Simulator");
                        /* Open the file "PmuServer.txt" in read mode */
                        FILE *file_1 = fopen ("PmuServer.txt","rb");
                        if (file_1 == NULL)
{
                                pmu_server();
                        }
                        else
{
                                fclose(file_1);
                                //validation_result ("\t\tPMU Server run successfully.\t\t\n");
                        }
                        /* Open the file "cfg2.bin" in read mode */
                        file_1 = fopen ("cfg2.bin","rb");
                        if (file_1 != NULL)
{
                                fclose(file_1);
                                create_cfg();
                                /* Disable the create Configuration button because cfg is already present in the system */
                                gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->create_cfg_button), FALSE);
                        }
                        else
{
                                /* Disable all buttons except create Configuration button because cfg is not present in the system */
                                gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->header_frm_button), FALSE);
                                gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->pmu_details_button), FALSE);
                                gtk_widget_set_sensitive(GTK_WIDGET(pmu_data->cfg_modification_button), FALSE);
                        }
                        /* Decorate the GUI */
                        pmu_colors();
                        /* Signal handling for buttons on  Main PMU Window */
                        g_signal_connect (pmu_data->create_cfg_button, "clicked", G_CALLBACK(cfg_create_function), NULL);
                        g_signal_connect (pmu_data->header_frm_button, "clicked", G_CALLBACK(hdr_create_function), NULL);
                        g_signal_connect (pmu_data->cfg_modification_button, "clicked", G_CALLBACK(cfg_chng_options), NULL);
                        g_signal_connect (pmu_data->pmu_details_button, "clicked", G_CALLBACK(show_pmu_details), NULL);
                        g_signal_connect (pmu_data->exit_button, "clicked", G_CALLBACK (destroy), NULL);
                        g_signal_connect (pmu_data->about_menuitem, "button_press_event", G_CALLBACK(about_pmu), NULL);
                        g_signal_connect (pmu_data->exit_menuitem, "button_press_event", G_CALLBACK(destroy), NULL);
                        g_signal_connect (pmu_data->E_button, "clicked", G_CALLBACK(destroy), NULL);
                        g_signal_connect_swapped (pmu_data->Pmu_Simulator, "destroy", G_CALLBACK (destroy), NULL);
                        /* Destroy builder, since we don't need it anymore */
                        g_object_unref(G_OBJECT(builder));
                        /* Show window. All other widgets are automatically shown by GtkBuilder */
                        gtk_widget_show(pmu_data->Pmu_Simulator);
                        /* GTK Main */
                        gtk_main();
                        /* Free any allocated data */
                        g_slice_free(pmuStruct, pmu_data);
                }
                return(0);
        }