iPDC-(PhasorDataConcentrator): dallocate.h File Reference
dallocate.h File Reference
Functions
void free_cfgframe_object (struct cfg_frame *cfg)
void free_dataframe_object (struct data_frame *)
void free_2darray (unsigned char **array, int x)
Function Documentation
void free_2darray (unsigned char ** array, int x)
Definition at line 164 of file dallocate.c.
References i.
Referenced by free_cfgframe_object(), and free_dataframe_object().
{
        int i;
        for(i = 0; i < n; i++)
                free(array[i]);
        free(array);
}
void free_cfgframe_object (struct cfg_frame * cfg)
Definition at line 53 of file dallocate.c.
References channel_names::angnames, for_each_pmu::annmr, for_each_pmu::anunit, for_each_pmu::cfg_cnt, for_each_pmu::cnext, for_each_pmu::data_format, cfg_frame::data_rate, dgnames::dg_next, dgnames::dgn, for_each_pmu::dgnmr, for_each_pmu::dgunit, channel_names::first, for_each_pmu::fmt, for_each_pmu::fnom, fp_log, cfg_frame::fracsec, cfg_frame::framesize, free_2darray(), cfg_frame::idcode, for_each_pmu::idcode, cfg_frame::num_pmu, channel_names::phnames, for_each_pmu::phnmr, for_each_pmu::phunit, cfg_frame::pmu, cfg_frame::soc, for_each_pmu::stn, cfg_frame::time_base, and to_intconvertor().
Referenced by cfgparser(), and remove_llnode().
{
        int j = 0;
        unsigned int phn,ann,dgn,num_pmu;
        struct dgnames *t_dgnames,*r_dgnames;
        fprintf(fp_log,"Inside free_cfgframe_object()\n");
        num_pmu = to_intconvertor(cfg->num_pmu);
        while(j<num_pmu) {
                free(cfg->pmu[j]->stn);
                free(cfg->pmu[j]->idcode);
                free(cfg->pmu[j]->data_format);
                free(cfg->pmu[j]->fmt);
                // Extract PHNMR, DGNMR, ANNMR
                phn = to_intconvertor(cfg->pmu[j]->phnmr);
                ann = to_intconvertor(cfg->pmu[j]->annmr);
                dgn = to_intconvertor(cfg->pmu[j]->dgnmr);
                if(phn != 0)
                free_2darray(cfg->pmu[j]->cnext->phnames,phn);
                if(ann != 0)
                free_2darray(cfg->pmu[j]->cnext->angnames,ann);
                if(dgn != 0) {
                        t_dgnames = cfg->pmu[j]->cnext->first;
                        while(t_dgnames != NULL) {
                                r_dgnames = t_dgnames->dg_next;
                                free_2darray(t_dgnames->dgn,16);
                                t_dgnames = r_dgnames;
                        }
                }
                if(phn != 0)
                free_2darray(cfg->pmu[j]->phunit,phn);
                if(ann != 0)
                free_2darray(cfg->pmu[j]->anunit,ann);
                if(dgn != 0)
                free_2darray(cfg->pmu[j]->dgunit,dgn);
                free(cfg->pmu[j]->phnmr);
                free(cfg->pmu[j]->annmr);
                free(cfg->pmu[j]->dgnmr);
                free(cfg->pmu[j]->fnom);
                free(cfg->pmu[j]->cfg_cnt);
                j++;
        } // End of While
        free(cfg->framesize);
        free(cfg->idcode);
        free(cfg->soc);
        free(cfg->fracsec);
        free(cfg->time_base);
        free(cfg->data_rate);
        free(cfg->num_pmu);
        free(cfg);
}
void free_dataframe_object (struct data_frame *)
Definition at line 124 of file dallocate.c.
References data_for_each_pmu::analog, data_for_each_pmu::annmr, data_for_each_pmu::dfreq, data_for_each_pmu::dgnmr, data_for_each_pmu::digital, data_frame::dpmu, fp_log, data_frame::fracsec, data_frame::framesize, free_2darray(), data_for_each_pmu::freq, data_frame::idcode, data_for_each_pmu::phasors, data_for_each_pmu::phnmr, data_frame::soc, and data_for_each_pmu::stat.
Referenced by assign_df_to_TSB(), and clear_TSB().
{
        int j = 0;
        fprintf(fp_log,"Inside free_dataframe_object()\n");
        // Free the blocks
        while(j < df->num_pmu) {
                if(df->dpmu[j]->stat[1] == 0x0F) {
                        free(df->dpmu[j]->stat);
                        j++;
                        continue;
                }
                free(df->dpmu[j]->stat);
                free(df->dpmu[j]->freq);
                free(df->dpmu[j]->dfreq);
                if(df->dpmu[j]->phnmr != 0)
                        free_2darray(df->dpmu[j]->phasors,df->dpmu[j]->phnmr);
                if(df->dpmu[j]->annmr != 0)
                                free_2darray(df->dpmu[j]->analog,df->dpmu[j]->annmr);
                if(df->dpmu[j]->dgnmr != 0)
                        free_2darray(df->dpmu[j]->digital,df->dpmu[j]->dgnmr);
                j++;
        } // End of While
        free(df->framesize);
        free(df->idcode);
        free(df->soc);
        free(df->fracsec);
        free(df);
}