PMUSimulator: function.h File Reference
function.h File Reference
Functions
void B_copy (unsigned char main[], unsigned char tmp[], int ind, int n)
void H2S (char a[], unsigned char temp_6[])
void i2c (int t, unsigned char temp[])
void li2c (long int t1, unsigned char temp_1[])
void f2c (float f, unsigned char temp_4[])
int c2i (unsigned char temp_2[])
long int c2li (unsigned char temp_3[])
uint16_t compute_CRC (unsigned char *message, char length)
void sigchld_handler (int s)
Function Documentation
void B_copy (unsigned char main[], unsigned char tmp[], int ind, int n)
Definition at line 64 of file function.c.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
        {
                int k;
                for(k=0; k<n; k++)
                {
                        main[ind+k] = tmp[k];
                }
        };
int c2i (unsigned char temp_2[])
Definition at line 144 of file function.c.
References i.
Referenced by create_cfg(), frame_size(), new_pmu_tcp(), and pmu_udp().
        {
                int i;
                i = temp[0];
                i<<=8;
                i |=temp[1];
                return(i);
        }
long int c2li (unsigned char temp_3[])
Definition at line 160 of file function.c.
References i.
Referenced by create_cfg().
        {
                long int i;
                unsigned char a[4];
                memset(a, '\0', 4);
                strcpy((char *)a, (char *)temp_3);
                i = a[0];
                i<<=8;
                i |=a[1];
                i<<=8;
                i |=a[2];
                i<<=8;
                i |=a[3];
                return(i);
        }
uint16_t compute_CRC (unsigned char * message, char length)
Definition at line 183 of file function.c.
References i, and temp.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
        {
                uint16_t crc=0x0ffff,temp,quick;
                int i;
                for(i=0;i<length;i++)
                {
                        temp=(crc>>8)^message[i];
                        crc<<=8;
                        quick=temp ^ ( temp >>4);
                        crc ^=quick;
                        quick<<=5;
                        crc ^=quick;
                        quick <<=7;
                        crc ^= quick;
                }
                return crc;
        }
void f2c (float f, unsigned char temp_4[])
Definition at line 124 of file function.c.
References i, and j.
Referenced by generate_data_frame().
        {
                int i, j;
                float fv;
                unsigned char a1[sizeof fv];
                fv = f;
                memcpy(a1, &fv, sizeof fv);
                for (i=0, j=3; i<sizeof fv; i++, j--)
                {
                        temp_1[j] = a1[i];
                }
        }
void H2S (char a[], unsigned char temp_6[])
Definition at line 79 of file function.c.
        {
                int k;
                for(k=0; k<16; k++)
                {
                        a[k] = temp_6[k];
                }
                a[16] = '\0';
        }
void i2c (int t, unsigned char temp[])
Definition at line 96 of file function.c.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
        {
                temp[0] = t>>8;
                temp[1] = t;
        }
void li2c (long int t1, unsigned char temp_1[])
Definition at line 109 of file function.c.
Referenced by create_cfg(), generate_data_frame(), header_frm_gen(), and reconfig_cfg_CC().
        {
                temp_1[0] = t1>>24;
                temp_1[1] = t1>>16;
                temp_1[2] = t1>>8;
                temp_1[3] = t1;
        }
void sigchld_handler (int s)
Definition at line 208 of file function.c.
Referenced by start_server().
        {
                while(wait(NULL) > 0);
        }